### ISSUE TITLE
Add support for SQL EXISTS and exists-based JOIN

### ISSUE THREAD

**Issue by GoogleCodeExporter** [npgall/cqengine#10]
```
Add support to query against foreign collections, similar to SQL EXISTS.

SELECT * From LocalCollection
WHERE EXISTS (
    SELECT * FROM ForeignCollection
    WHERE LocalCollection.localAttribute = ForeignCollection.foreignAttribute
)

This would enable joins between indexed collections.
```

Original issue reported on code.google.com by `ni...@npgall.com` on 27 Jan 2013 at 10:07

**Comment by AnnDangPham** [comment]
Hi Niall, I've been looking at using cqengine for a project and came across this functionality you added.  When I try to use the SQL WHERE EXISTS statement as in the example above with the SQLParser, I keep getting parser failure: 
Request was not successful: Failed to parse query at line 1:30: extraneous input 'EXISTS' expecting {'(', K_NOT, IDENTIFIER, STRING_LITERAL}

Browsing through the examples in your test, I'm guessing this functionality has only been added to the CQN dialects, but not currently supported in SQL parser?

Thanks,
Ann

**Comment by AnnDangPham** [comment]
See Niall's reply at https://groups.google.com/forum/#!topic/cqengine-discuss/V-GsNSPIHAA.
