### ISSUE TITLE
ExistsIn query performance

### ISSUE THREAD

**Issue by uujava** [npgall/cqengine#102]
I have two collections with something like master-detail relation (ForeignKey -> PrimaryKey  in database terms). I basically need to perform, in most primitive form, a query like this:
```
 Query<Item> query = QueryFactory.and(QueryFactory.equal(ID, randomId()), QueryFactory.existsIn(secondCollection, ID, EID));
Item result = firstCollection.retrieve(query).iterator().next();
```
Collections are indexed by ID (UniqueIndex - like primary key) and EID (HashIndex - foreign key) respectively.
I've put JMH benchmark to strip off my project specifics and compare different options of retrieving results: https://github.com/uujava/cqengine-query-jmh 
And got the results I could not explain: https://github.com/uujava/cqengine-query-jmh/releases/tag/initial_version

Comparing a case `QueryTest.streamJoin`
```
    @Benchmark
    public void streamJoin(Blackhole bh) {
        Long value = randomId();
        Equal<Long, Long> equal = QueryFactory.equal(EID, value);
        Long result = StreamSupport.stream(second.retrieve(equal).spliterator(), false).map(found -> {
            Equal<Long, Long> subQ = QueryFactory.equal(ID, found);
            return first.retrieve(subQ).iterator().next();
        }).findFirst().get();
        bh.consume(result);
    }
```
With a case `QueryTest.uniqueExistsJoin`
```
    @Benchmark
    public void uniqueExistsJoin(Blackhole bh) {
        Query<Long> query = QueryFactory.and(QueryFactory.equal(ID, randomId()), QueryFactory.existsIn(second, ID, EID));
        bh.consume(first.retrieve(query).iterator().next());
    }
```

I've got 
434088,196 vs 12,434 -> 35000 times difference.

jmh with -prof stack reveals that the `QueryTest.uniqueExistsJoin` most time spent in:
```
 55.2%  55.2% java.util.concurrent.ConcurrentHashMap$Traverser.advance
 44.3%  44.3% java.util.AbstractSet.hashCode
```
I guess calculating hashCode on a big set of something.

Not sure if it's an issue, or my misuse of existsIn API.

**Comment by uujava** [comment]
Seems found the code where hashCode is calculated in ExistsIn:
```
    @Override
    protected int calcHashCode() {
        int result = foreignCollection.hashCode();
        result = 31 * result + localKeyAttribute.hashCode();
        result = 31 * result + foreignKeyAttribute.hashCode();
        result = 31 * result + (foreignRestrictions != null ? foreignRestrictions.hashCode() : 0);
        return result;
    }
```

It' takes a lot for 1M objects in foreignCollection.

**Comment by uujava** [comment]
Propose a fix:
 - check standing query befor calculating query.hashCode - just to avoid hashCode calculation for collections where no standing index defined
 - use identityHashCode for foreignCollection

**Comment by uujava** [comment]
Got better values but still 2 times difference:
```
QueryTest.streamJoin                      true  thrpt    2    415448,120          ops/s
QueryTest.streamJoin                     false  thrpt    2    444907,338          ops/s
QueryTest.uniqueExistsJoin                true  thrpt    2    257267,062          ops/s
QueryTest.uniqueExistsJoin               false  thrpt    2    272811,419          ops/s
```

**Comment by uujava** [comment]
Please consider another performance pull request https://github.com/npgall/cqengine/pull/105 for review.

**Comment by npgall** [comment]
That's indeed a potential bottleneck in the ExistsIn query - nice find!

The calcHashCode() method is called when the hashCode needs to be computed the first time, and then it's subsequently cached. But if it's expensive to compute it the first time, then this will be a problem. The reason the hashCode is cached is to improve performance in StandingQueryIndexes. But of course this won't help if there are no such indexes.

So I like your idea to simply avoid the computation entirely. I will take a look at that.

**Comment by npgall** [comment]
It doesn't look like #105 is related to this ExistsIn issue, right? Could you create a separate issue for discussing #105?

**Comment by uujava** [comment]
Thanks for quick response. Note that the patch is also uses identityHashCode which is proper method it would be documented that ExistsIn properly works on same instance of foreignQuery.

**Comment by uujava** [comment]
Created issue #106 to discuss pull request #105

**Comment by npgall** [comment]
How about this? https://github.com/npgall/cqengine/commit/14e67e04d74468f7bac7e2932be9c29fe67f9760
