### ISSUE TITLE
Unable to add objects to Off-Heap collection

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#114]
```
public static class Test1 {

        private String id;

        public Test1() {
            this.id = UUID.randomUUID().toString();
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public static final SimpleAttribute<Test1, String> ID_INDEX = new SimpleAttribute<Test1, String>() {
            @Override
            public String getValue(Test1 test1, QueryOptions queryOptions) {
                return test1.getId();
            }
        };
    }

public static void main(String args[]) {
        try {
            IndexedCollection indexedCollection = new ConcurrentIndexedCollection<>(OffHeapPersistence.onPrimaryKey(Test1.ID_INDEX));
            Test1 test1 = new Test1();
            indexedCollection.add(test1);
            System.out.println(indexedCollection);
        } catch (NullPointerException ex) {
            Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
```

Why does this class throw a `java.lang.NullPointerException`?

**Comment by npgall** [comment]
This is because your `SimpleAttribute` will return null, which is not allowed. See [null values](https://github.com/npgall/cqengine#null-values) for more information.

To fix it, you can use a `SimpleNullableAttribute` instead, which is permitted to return null.

**Comment by bluedoo** [comment]
Why will my `SimpleAttribute` return null? Because it's a new collection?

**Comment by npgall** [comment]
Sorry I missed the part where the constructor assigns a value to the id. I thought the id was null.
If the id can't be null, then I see no reason why this would throw an NPE.

I've just run the test case on my machine and it does not throw an NPE for me. 
Can you double check that it definitely throws an NPE for you and provide the stack trace?

**Comment by bluedoo** [comment]
Apologies, error on my part, the `toString()` method (redacted above) was throwing the NPE.
