### ISSUE TITLE
-shm and -wal files being created with undeleteable lock

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#115]
Using disk persistence, I specify a file to save the collection to but then another two files get created, one with -shm appended to the filename and the other with -wal appended to the filename.

What are these files?

What triggers these files to be created?

How do you delete these files? I've tried using a force delete from commons-io but no luck... i.e.:

```
FileDeleteStrategy.FORCE.delete(file);
```

**Comment by npgall** [comment]
Those are temporary files which should be deleted automatically when your application has finished using CQEngine - i.e. when it has closed all of the ResultSets it was using or has finished adding objects to the collection.

The "-wal" file is the Write-Ahead Log file belonging to SQLite, and the "-shm" file is a shared memory file, which also relates to SQLite. You can read more about these [here](https://www.sqlite.org/tempfiles.html).

CQEngine uses SQLite for disk persistence, and specifically it enables [WAL mode](https://www.sqlite.org/wal.html) in SQLite, which causes these files to be created.

**Comment by bluedoo** [comment]
How do you tell CQEngine that you're done? Is there a way? When running tests to create data and then verify if it's been created, I run into the above issue and can't delete the collection file once the test is done

**Comment by npgall** [comment]
Check that your code is calling ResultSet.close() when it's done. This should be the only thing that's needed.

**Comment by bluedoo** [comment]
Thanks, closing the `ResultSet` worked for me
