### ISSUE TITLE
cqengine-lite

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#125]
Would it be possible to get a "lite" version of this which is just purely java, no other dependencies?

**Comment by npgall** [comment]
It should already be possible. You can exclude the dependencies such as Xerial/SQLite, and the library should work fine so long as you only use the on-heap persistence and indexes.

**Comment by bluedoo** [comment]
@npgall I also want FilePersistence though, is there a way to have cqengine (OnHeap and File persistence) with pure java? (i.e. no maven dependencies)

**Comment by npgall** [comment]
Yes. You can use the _shaded_ build of CQEngine which contains all of CQEngine's dependencies.

Add `<classifier>all </classifier>` to your dependency on CQEngine, and exclude all of CQEngine's dependencies.

**Comment by bluedoo** [comment]
@npgall It would be cool if there was a separate set of code and a separate dependency, a "lite" version altogether. The objective here would be smaller devices, smaller, simpler set of code; different objectives to the full version.

For the time being I will use the above recommendation though

**Comment by npgall** [comment]
I do see what you mean about the potential benefit of maybe omitting the DiskIndex and OffHeapIndex classes in a pure Java version. However at the moment I don't think the benefits would outweigh the additional maintenance overhead it would introduce.

As I mentioned in https://github.com/npgall/cqengine/issues/127, pure Java does not support off-heap memory, and I'd like that CQEngine offered all of its current features by default. 

Essentially there already an "opt-out" mechanism - an intentionally soft dependency on SQLite - where you can omit the SQLite jar, and just avoid using the features which depend on it. So it's already possible to slim down the code you need to ship to constrained environments. The tradeoff is you just need to avoid using certain features. Hopefully that's enough for most people, for now anyway!
