### ISSUE TITLE
Maven 2.9.3 is not working

### ISSUE THREAD

**Issue by peterdn1** [npgall/cqengine#126]
DOES NOT WORK:
  
        <dependency>
            <groupId>com.googlecode.cqengine</groupId>
            <artifactId>cqengine</artifactId>
            <version>2.9.3</version>
        </dependency>
WORKS:
  
        <dependency>
            <groupId>com.googlecode.cqengine</groupId>
            <artifactId>cqengine</artifactId>
            <version>2.9.2</version>
        </dependency>

**Comment by npgall** [comment]
Can you define "does not work"?

**Comment by peterdn1** [comment]
From intelligJ - Dependency "'com.googlecode.cqengine:2.9.3'" not found

Is cqengine-2.9.2.pom in the 2.9.3 repository?

**Comment by peterdn1** [comment]
Sorry please close the issue it was an issue with my environment.
