### ISSUE TITLE
javadocs don't download in netbeans

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#128]
not sure how you create the link but I've noticed that after clicking "Download Javadocs" then pressing ctrl+space on a cqengine method, the javadocs do not show. This applies to the latest version of netbeans.

<img width="435" alt="screen shot 2017-04-04 at 10 45 34 am" src="https://cloud.githubusercontent.com/assets/23420787/24651059/3ca05868-1924-11e7-85f3-13a2b8854878.png">
<img width="677" alt="screen shot 2017-04-04 at 10 49 16 am" src="https://cloud.githubusercontent.com/assets/23420787/24651098/633deca6-1924-11e7-8c30-e68a026c762e.png">

**Comment by npgall** [comment]
I doubt this is a problem with CQEngine as JavaDocs have always been uploaded to Maven central, and they do seem to be present there for the latest version: http://repo1.maven.org/maven2/com/googlecode/cqengine/cqengine/2.9.3/

Can you double-check that your IDE is configured correctly? And maybe test in a different IDE also? 
I will close this issue for now as JavaDocs are present in maven central. Please let me know if you have more findings though!
