### ISSUE TITLE
convert IndexedCollection to List/Set/Map

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#130]
Is there a way to cast from one collection to another without much cost in performance? Are there examples on how to do this somewhere?

**Comment by npgall** [comment]
You can't cast, but you can wrap an `IndexedCollection` around an existing regular collection if you want, using `WrappingPersistence`. You can find an example [here](https://github.com/npgall/cqengine#persistence-on-heap-off-heap-disk).

**Comment by bluedoo** [comment]
@npgall so if you want to convert from an `IndexedCollection` then you have to copy?
