### ISSUE TITLE
recommended way to perform an update in an IndexedCollection

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#132]
Is it best to just use `.remove(foo)` then `.add(newFoo)`? What's the recommended approach for updates?

**Comment by npgall** [comment]
Duplicate of https://github.com/npgall/cqengine/issues/133

**Comment by bluedoo** [comment]
Here is an example of the recommended approach:

https://github.com/npgall/cqengine/blob/master/code/src/test/java/com/googlecode/cqengine/examples/replace/Replace.java
