### ISSUE TITLE
what happens when you update an object?

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#133]
If I save a million instances of `Foo` using DiskPersistence:

```
class Foo {
public String id;
public String name;
}
```

Then I change the class to the following:

```
class Foo {
public String id;
public Integer age;
}
```

What will happen to the objects in the collection next time I try to read the collection and what happens to the indexes?

Are there any potential issues that could occur when changing data structures?

**Comment by npgall** [comment]
This is similar to https://github.com/npgall/cqengine/issues/131. You can see that question for details.
