### ISSUE TITLE
Limit Queries to a Subrange

### ISSUE THREAD

**Issue by sirinath** [npgall/cqengine#136]
Is it possible to add the ability to limit queries to a subrange.  E.g. `retrieve(query, 10, 100)`

**Comment by npgall** [comment]
You can a use a CQEngine between() query to restrict the Results to a
subrange of values in your data.

Or did you mean something like SQL LIMIT?

For this you can use a 3rd party library such as Guava's Iterables.limit()
to return only the first x items in a ResultSet.
https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/Iterables.html#limit-java.lang.Iterable-int-


Alternatively if you mean to paginate results, you could pass the ResultSet
to a 3rd party pagination library.

Hope that helps!

**Comment by sirinath** [comment]
It is like between but based on the the nth items added. Say anything older than 100th items in the past is stale. Also say we have added 10 new items but ou processing is lagging. So should be able to exclude these items until you catch up.

**Comment by sirinath** [comment]
Another minor concern about this is overhead in memory and search beyond the needed window. Should be able to expand and contract the window as needed.

**Comment by npgall** [comment]
Can you use a timestamp or sequence number for this?
That is, retrieve objects where sequence number is greater than the last
fetched sequence number.


On 2 May 2017 07:30, "Suminda Dharmasena" <notifications@github.com> wrote:

Another minor concern about this is overhead in memory and search beyond
the needed window. Should be able to expand and contract the window as
needed.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/npgall/cqengine/issues/136#issuecomment-298652712>, or mute
the thread

**Comment by sirinath** [comment]
If the required window is tiny relative to the index length will this justify the overhead?

**Comment by npgall** [comment]
I'm not sure i understand your requirements. Based on your last mail it
sounds like you need a queue then?

**Comment by sirinath** [comment]
I want a moving window of data with the possibility to unused portion swapped out of memory to hard disk.

**Comment by sirinath** [comment]
One of the use case is. Say you have price data, your result set cannot return tomorrows when you are at a point in time. Another bact test can be at another point in time. Also say each looks back only x days only you need a result sets such that by sliding this window forward and backwards you get the needed sub set of results.

**Comment by npgall** [comment]
You can use a `between()` query to restrict results to a particular range of timestamps. So I think this should allow you to omit tomorrow's data etc.

However regarding your earlier comment - to swap the unused portion out of memory...

If you use `DiskPersistence` then CQEngine actually will page in and out the data being accessed. So if your application stops using a portion of your data then it actually will not be loaded. 

CQEngine relies on SQLite for this behavior and you can customize the number of pages kept in memory by supplying _override properties_ to [DiskPersistence.html.onPrimaryKeyInFileWithProperties](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/persistence/disk/DiskPersistence.html#onPrimaryKeyInFileWithProperties-com.googlecode.cqengine.attribute.SimpleAttribute-java.io.File-java.util.Properties-). You can override any setting which can be set via a SQLite PRAGMA statement; for example: [cache_size](https://sqlite.org/pragma.html#pragma_cache_size). You can find an example of how to override a default setting [here](https://github.com/npgall/cqengine/blob/2.9.3/code/src/test/java/com/googlecode/cqengine/persistence/disk/DiskPersistenceConcurrencyTest.java#L85). 

OTOH, you will get much better performance if your data can be kept on the Java heap (default aka `OnHeapPersistence`). So for best performance you could consider partitioning your data by day, into multiple `IndexedCollection`s, and then maybe removing older collections from memory when they are no longer needed. You would need to send your queries to multiple IndexedCollections, and do a set-union of the ResultSets. However you can leverage CQEngine's [ResultSetUnionAll](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/resultset/connective/ResultSetUnionAll.html) class for this.

Anyway I hope that helps! I'll close this issue for now - we can reopen if necessary.

Best regards,
Niall
