### ISSUE TITLE
updating objects with file storage

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#137]
if you have a .dat file which contains all your beans and then you update the bean class and introduce some new fields or remove some fields then attempt to pick up the .dat file and continue using it with the new configuration, an exception is thrown.

What is the best way to perform updates?

**Comment by npgall** [comment]
This is a complicated question :)

The serialization format used by CQEngine does not support backwards or forwards compatibility. Technically, the underlying serialization library which CQEngine uses - [Kryo](https://github.com/EsotericSoftware/kryo#compatibility) - does support this to a degree, but there would be disadvantages in exposing or using that support.

So one workaround/option would be to store your IndexedCollection in a file where the file name contains some kind of version number for the schema (the set of fields) in your beans. This way at application startup, if a .dat file for the current version of your bean schema was not already on disk, your application could recreate a new .dat file containing beans for the new version.

Hope that helps!
Niall
