### ISSUE TITLE
comparing IndexedCollection contents using equals()

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#138]
I don't see any overriding implementation of `equals()` in the class. Is it safe to assume that using `equals()` to compare two IndexedCollections will result in `true` when the contents are the same and `false` when the items in the collection are different?

**Comment by npgall** [comment]
The IndexedCollection actually does implement [equals()](https://github.com/npgall/cqengine/blob/2.9.3/code/src/main/java/com/googlecode/cqengine/ConcurrentIndexedCollection.java#L511) in accordance with the contract of java.util.Set. So yes you can rely on this behaviour :)

Hope that helps!
