### ISSUE TITLE
Query - Method undefined

### ISSUE THREAD

**Issue by CreeperLava** [npgall/cqengine#139]
I want to use queries in a database, but am constantly getting a "The method [method used by query] is undefined for the type [class]".

I've used the Readme and the [introduction](https://github.com/npgall/cqengine/tree/master/code/src/test/java/com/googlecode/cqengine/examples/introduction) tutorial as a learning base. What confuses me is that the very examples given in the readme / tutorial also have this issue.
For example, when I tried to copy-paste the 2 classes from the introduction tutorial :
![](http://i.imgur.com/kvpupTj.png)
"The method contains(Attribute<Car,String>, String) is undefined for the type Introduction"
Side note on the tutorials from github : the imports would need to be updated (the paths changed in 2 years, I suppose).

Here is an example of code I would like to be able to use :
`Query<Texture> query = equal(Texture.CRC, texture.getCrc());`

I have no doubt this is very likely to be an error from my part, not from cqengine. Thus, I'd appreciate any advice on the correct syntax to use for Queries !

**Comment by CreeperLava** [comment]
If anyone is interested, I found a workaround to be able to use queries. I'd love to know why the above examples don't work, though.

```
Query<Object> query = new Equal<Object, String>(Object.attribute, foo); // Replace Equal with Or, And, etc. Find the entire list of supported objects (here)[https://github.com/npgall/cqengine/tree/master/code/src/main/java/com/googlecode/cqengine/query]
for(Object t : database.retrieve(query)){
	//...
}
```

**Comment by npgall** [comment]
I think you might have forgotten to add the static import statement, which provides access to the queries. This actually is mentioned in the documentation and is included in the introduction example :)

Anyway adding the following to the top of your class should fix the problem for you:

`import static com.googlecode.cqengine.query.QueryFactory.*;`

Let me know if the problem persists though!

**Comment by CreeperLava** [comment]
I can't believe it was something that simple. Thank you !
