### ISSUE TITLE
change method "addIndex" to "addIndexIfNotExists"

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#140]
in theory you'd never add the index twice right? perhaps it should just return a `Boolean` to confirm if it added it or if it already existed?

**Comment by bluedoo** [comment]
Alternatively, this method can check for you:

```
public Boolean containsIndex(final IndexedCollection indexedCollection, final SimpleAttribute simpleAttribute) {
        Iterable iterable = indexedCollection.getIndexes();
        for (Object object : iterable) {
            if (object.equals(simpleAttribute)) {
                return Boolean.TRUE;
            }
        }
        return Boolean.FALSE;
    }
```

**Comment by npgall** [comment]
This is actually not as easy as it sounds unfortunately..

If you don't add more than one index on each attribute, and only use the on-heap indexes, then the approach indeed above should work. However it is actually permitted to add multiple indexes (typically of different types) on the same attribute, so in applications which leverage that, this approach might not work.

Another complication is that it's also permitted for applications to plug in custom application-defined indexes which might not implement equals() correctly. 

So unfortunately the current API is like this for the reasons above.

If you can think of a better solution you could submit a pull request, but I'm afraid I can't currently think of a better way. Hope that helps!
