### ISSUE TITLE
disable persistence of nested objects and use references instead

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#145]
if I keep an object nested in another object will it be saved in two places?

Say I have a `User` object which contains a `List<Picture>`. Both objects are being stored using File persistence `IndexedCollection`. 

Will all pictures be saved in `pictures.dat` AND `users.dat` or will `users.dat` just contain a list of references to pictures inside `pictures.dat`?

What is the recommended approach here?

**Comment by npgall** [comment]
It depends on the type of persistence configured. 

If the collection is using OnHeapPersistence (the default), then object references will be used. All indexes will store only pointers/references, and so each Picture object will only be stored on the heap once.

However if the collection is using OffHeapPersistence or DiskPersistence, then object references will not be used, but foreign key references will be used instead - which gives a kind of similar behavior. 

Basically when you configure DiskPersistence, you tell CQEngine which attribute to use as a primary key for your objects. CQEngine will then build a special _clustered_ index on the primary key, which stores the primary key values AND a serialized form of your POJOs on disk next to each other. This allows your objects to be looked up by primary key later, and deserialized onto the heap again as needed.

When you add secondary indexes to the collection, CQEngine will use a different type of index - a _non-clustered_ index. In this case the values from the attributes in your secondary index will be stored on disk, but in this case CQEngine will NOT store a serialized copy of your POJOs next to them. It will store the primary keys of the corresponding POJOs next to those values instead _(aka a foreign key - when a primary key is stored in a foreign index, it is known as a foreign key in that index)_. 

Subsequently when CQEngine looks up an object via a secondary index, it's actually a 2-step operation. It will first retrieve the foreign key from the secondary index, and then it will retrieve the actual POJO from the primary key index. _(At least, that's a brief summary of what happens. There are some nuances which you can read about in [MergeStrategies.md](https://github.com/npgall/cqengine/blob/master/documentation/MergeStrategies.md).)_

Hope that helps!

**Comment by npgall** [comment]
Just an additional side note -

Note if you configure DiskPersistence, then by default the IndexedCollection and all of the indexes configured on it will be stored in a _single file on disk_. So there would not actually be a `pictures.dat` and a `users.dat` file by default. There would just be a single `collection.dat` file (or whatever you named it). 

You can override this default behaviour to store some indexes in separate files if you want, but that would not normally be required. If you really did configure multiple files persistence files though, it would still work in the same way. The foreign key references in a secondary (non-clustered) index stored in one file, would simply refer to items in the primary key (clustered) index stored in the other file.

**Comment by bluedoo** [comment]
@npgall so when you call `indexedCollection.remove(o);` while using `DiskPersistence` will all nested objects be deleted too or only the references to them?

**Comment by npgall** [comment]
Both the object itself and the references to it will be deleted.
