### ISSUE TITLE
Question - how best to construct a fallback query (if/else within the query)

### ISSUE THREAD

**Issue by beirtipol** [npgall/cqengine#147]
I'm sure I just can't find the right words to look for in the documentation to acheive this! I'm sure I can do this by just retrieving the first set and applying my own logic, but wondering if there was built in functionality for this

Given the following example, I would like to filter in the following order (My real example has an unfortunately convoluted set of rules)

- Find cars that are model "ford escort"
- If no cars found, then just return "ford.*"
- Then search on wheels==5
- If no cars found, then any number of wheels

```
// Car( number, model, doors)
cars.add(new Car(1, "ford focus", 3);
cars.add(new Car(2, "ford taurus", 5);
cars.add(new Car(3, "honda civic", 4);

```

**Comment by npgall** [comment]
The best option is probably to retrieve ResultSets for all of those queries, and then concatenate those into a single ResultSet:
```java
public static <O> ResultSet<O> concatenate(ResultSet<O>... resultSets) {
    List<ResultSet<O>> resultSetList = Arrays.asList(resultSets);
    Query<O> union = new Or<>(
            resultSetList.stream().map(ResultSet::getQuery).collect(Collectors.toList())
    );
    return new ResultSetUnionAll<>(resultSetList, union, QueryFactory.noQueryOptions());
}
```

CQEngine uses lazy evaluation and results are only computed on-the-fly while the application iterates through the ResultSet(s). So concatenating ResultSets like this is basically free. The results from the later queries will not be computed until (or unless) the application has first iterated through the result from the earlier queries. Hope that helps!

**Comment by beirtipol** [comment]
Legendary, cheers Niall!

**Comment by beirtipol** [comment]
Started looking at your suggestion today and I don't think it quite works with what I'm trying to do. Probably worth going in to a cut down version of my convoluted real life example!

The IndexedCollection I'm creating is for mapping a set of parameters to a specific Strategy. There are a few quirks in the lookup logic that I'm trying to fit in to cqengine (I'm very happy to restructure the mapping data to better fit cqengine as our legacy lookup logic is massively complicated)

- Filter the resultset by columns in order of search, i.e. Product, then ProductType, then Desk
- Try and match on an exact value or regex. If you can't find either of those, retain rows where the value is "ALL"
- The lookup table is "maintained" in such a way that only one row should be returned for any query, but it's certainly possible that multiple results could be returned

Product | ProductType | Desk | Strategy
--- | --- | --- | ---
CreditDefaultSwap | ALL | ALL | RTP987
CreditDefaultSwap | CDSABSIndex | ALL | ABC123
CreditDefaultSwap | CDSIndexTranche | ALL | BCD789
CreditDefaultSwap | CDSIndexTranche | BeirtiDesk | ABC456
CreditDefaultSwap | CDSIndexTranche | (.*)Rates | EFG234


I query the lookup table with 'Product', 'ProductType, 'Desk'. So:

- CreditDefaultSwap | RecoveryLock | BeirtiDesk == RTP987
- CreditDefaultSwap | CDSABSIndex | SomeMagicDesk == ABC123
- CreditDefaultSwap | CDSIndexTranche | NiallDesk == BDC789 
- CreditDefaultSwap | CDSIndexTranche | BeirtiDesk == ABC456 
- CreditDefaultSwap | CDSIndexTranche | BeirtiDeskRates == EFG234 
- CreditDefaultSwap | CDSIndexTranche | NiallDeskRates == EFG234 


Here's how I'd imagine the query being built in 'simple' language but I appreciate that it probably doesn't fit with how the query objects are executed. We'd need a 'firstQueryWithResults' which would execute each subquery and retain results as long as results > 0. We'd also need a reverse regex query where the collection's object is used as the regex against the value being passed in

```
Query<StrategyLookup> query = and(
  firstQueryWithResults( 
    valueMatchesRegex( PRODUCT, "CreditDefaultSwap" ), 
    equal( PRODUCT, "ALL" ) ),
  firstQueryWithResults( 
    valueMatchesRegex( PRODUCT_TYPE, "RecoveryLock" ), 
    equal( PRODUCT_TYPE, "ALL" ) ), 
  firstQueryWithResults( 
    valueMatchesRegex( DESK, "BeirtiDesk" ), 
    equal( DESK, "ALL" ) )
);
```

Hope that's more clear (and doesn't cause too much of a facepalm!)

**Comment by npgall** [comment]
(reopening)

It's quite difficult to index data to facilitate fast retrieval using regular expressions so I'm not sure if that would perform well.

Could you explain your requirement using SQL? As in, if the data was in an RDBMS, what SQL statements would you use to retrieve it? It's usually quite straightforward to translate SQL queries into CQEngine queries.

**Comment by beirtipol** [comment]
I'll try and translate it and come back to you, thanks

**Comment by npgall** [comment]
Closing this for now. Feel free to reopen if you need more info.
