### ISSUE TITLE
prevent duplicates from being added to IndexedCollection

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#148]
@npgall if you do:

```
if (!collection.contains(o)) {
 collection.add(o);
}
```

there's still a chance duplicate objects will be added in a concurrent environment right?

what's the recommended approach to add objects in a way that will completely avoid duplicates from ever being added?

**Comment by npgall** [comment]
The IndexedCollection is an implementation of java.util.Set, so it's best to just use the [Set.add()](http://docs.oracle.com/javase/7/docs/api/java/util/Set.html#add(E)) method which - 

_"Adds the specified element to this set if it is not already present (optional operation). More formally, adds the specified element e to this set if the set contains no element e2 such that (e==null ? e2==null : e.equals(e2)). If this set already contains the element, the call leaves the set unchanged and returns false. In combination with the restriction on constructors, this ensures that sets never contain duplicate elements."_

```java
boolean wasAdded = collection.add(o);
```
However.. if your application might try to add the same object concurrently, you should use the same method, but in CQEngine's [ObjectLockingIndexedCollection](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/ObjectLockingIndexedCollection.html) instead, which:

_"Extends ConcurrentIndexedCollection with some specialized locking for applications in which multiple threads might try to add or remove the same object to/from an indexed collection concurrently."_

Hope that helps!
