### ISSUE TITLE
application cannot start after stopping during data operation

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#149]
I have no idea how to replicate this issue but what I've noticed is that if I'm running my unit tests and then I terminate them halfway and then try to start them again, the application won't start, it just hangs...

I'm using `DiskPersistence` so when I delete all the `dat` files and then try to start it, it works fine, otherwise it just creates a `dat-shm` and `dat-wal` and stalls forever

Every time the application starts this line is run:

`public static final IndexedCollection<Foo> foos = new ConcurrentIndexedCollection<>(DiskPersistence.onPrimaryKeyInFile(Foo.ID_INDEX, new File("foos.dat")));`

**Comment by npgall** [comment]
Maybe the files are still locked. If you restart your computer without deleting the files beforehand, does it still happen after the restart? Which OS are you using?

The method of file locking can be adjusted, with various pros and cons: https://sqlite.org/vfs.html

**Comment by bluedoo** [comment]
I'm using WIndows 7 as a guest OS inside VirtualBox from an Ubuntu host

If I define `IndexedCollection<Foo> foos = new ConcurrentIndexedCollection<>(DiskPersistence.onPrimaryKeyInFile(Foo.ID_INDEX, new File("foos.dat")));` and add all the indexes on each operation then this problem does not occur but this is obviously not ideal in terms of performance

**Comment by npgall** [comment]
The problem above seems to be a NullPointerException at line 100 in the constructor of your Foo class, while your objects are being deserialized from disk.

It's curious that somehow a StackOverFlow error is reported as well though. Do you have any recursive or otherwise complex logic in the constructor?

**Comment by bluedoo** [comment]
@npgall yes it has a while loop in it but it immediately works when I move the instantiation of `IndexedCollection` from being `static` (once off) to initializing before each query

**Comment by npgall** [comment]
Are you creating an instance of the IndexedCollection, in the constructor of the POJO objects you will store in the collection? This sounds like a recipe for disaster :D

**Comment by bluedoo** [comment]
@npgall Ideally I would like to have an `Application.java` file that instantiates a `public static IndexedCollection` and a `static { ... }` block to add the indexes to the collection with. However, since this causes the above blocking issue I've now created a `Database.java` file that contains all my data operation methods such as `insert(Object obj)` and `Delete(Object obj)` and in each of these methods I instantiate the `IndexedCollection` and add their respective indexes which seems to work fine but as you've mentioned before, is not ideal in terms of performance

**Comment by npgall** [comment]
You should not need to cache the IndexedCollection in a static field. You can store it as an instance variable. Anyway, I will close this now as hopefully if you avoid the recursion the issue should go away. We can reopen if necessary.
