### ISSUE TITLE
retrieve n random objects

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#151]
Is there a query that can be written to obtain a specific number of random objects from an `IndexedCollection`?

I checked the documentation but couldn't find anything?

**Comment by npgall** [comment]
Not specifically, however you can use similar approaches as with SQL: [Select n random rows from SQL Server table](https://stackoverflow.com/questions/848872/select-n-random-rows-from-sql-server-table)

You could define an attribute for your POJOs which just returns a random number e.g. Car.RANDOM:

```java
public static final SimpleAttribute<Car, Integer> RANDOM = new SimpleAttribute<Car, Integer>("RANDOM") {
    final Random rand = new Random();
    public Integer getValue(Car car, QueryOptions queryOptions) { return rand.nextInt(); }
};
```

Then you could retrieve results ordered as follows:

```java
ResultSet<Car> carsOrderedRandomly = cars.retrieve(query, queryOptions(orderBy(ascending(Car.RANDOM))));
```
You can then read as many cars from that ResultSet as necessary. They will be returned in random order.

However - note that, **in common with the SQL approaches mentioned above, this approach has O(n) time complexity**. 

There might be better approaches. If they can be implemented in SQL I don't see a reason why they could not be applied to CQEngine in most cases. Hope that helps!

**Comment by ashtonhogan** [comment]
@npgall What should I do about `query` because I don't think there is a query, I just want to check the entire `Car` collection?

**Comment by npgall** [comment]
Sorry I forgot that bit! You can supply `all(Car.class)` for the query. It will match the entire collection.
