### ISSUE TITLE
GUI for Disk Persistence collection files

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#153]
It would be great if there were some sort of GUI for browsing data and making calls within the collection files. Something similar to MySQL workbench or the like. Please implement this.

**Comment by npgall** [comment]
Hi bluedoo,

CQEngine uses SQLite for disk persistence, so actually you can already use the following GUI tools to browse disk persistence files:

* [DB Browser for SQLite](http://sqlitebrowser.org/)
* [SQLiteStudio](https://sqlitestudio.pl/index.rvt)
* etc.

Hope that helps,
Niall

**Comment by bluedoo** [comment]
Hi @npgall 

I tried those but they're not that great because they just show objects as "BLOB"s. It would be more useful to have a GUI that actually let me explore the data...

Do you want to reopen this?

**Comment by npgall** [comment]
Hi bluedoo,

I would not have time to take on development of a dedicated GUI myself. This needs volunteers, not just a feature request :)

I think a GUI could indeed be useful, but it probably belongs in a separate project, in the same way as the SQLite GUIs above are separate from SQLite. Would you like to volunteer to do this?

This could either be implemented as (1) a brand new generic GUI over CQEngine (which would support on heap, off heap and disk persistence), leveraginging CQEngine's Java APIs to browse the collection and indexes; or (2) it could be implemented by plugging in a POJO deserializer into an existing SQLite GUI for visualizing blobs (which would support CQEngine's disk persistence only).

Do you have time to investigate this yourself? If so I'd be happy to support your efforts as best I can!

**Comment by muhdkhokhar** [comment]
It would be a great feature to create GUI.
