### ISSUE TITLE
update performance improment

### ISSUE THREAD

**Issue by zenzondon** [npgall/cqengine#154]
Hi
when I run following code, update() cost to much time.

import static com.googlecode.cqengine.query.QueryFactory.equal;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.googlecode.cqengine.ConcurrentIndexedCollection;
import com.googlecode.cqengine.IndexedCollection;
import com.googlecode.cqengine.index.hash.HashIndex;
import com.googlecode.cqengine.index.unique.UniqueIndex;
import com.googlecode.cqengine.query.Query;
import com.googlecode.cqengine.resultset.ResultSet;

public class CqengineTest {
    public static void main(String[] args) {
        IndexedCollection<FuturePosition> ftPositions = new ConcurrentIndexedCollection<FuturePosition>();
        ftPositions.addIndex(UniqueIndex.onAttribute(FuturePosition.INDEX_POS_UNIQUE));
        ftPositions.addIndex(HashIndex.onAttribute(FuturePosition.INDEX_POS_TRADINGACCOUNT));
        ftPositions.addIndex(HashIndex.onAttribute(FuturePosition.INDEX_POS_ASSETACCOUNT));
        ftPositions.addIndex(HashIndex.onAttribute(FuturePosition.INDEX_POS_SECURITY));
        List<FuturePosition> posList = new ArrayList<FuturePosition>();
        long now = System.currentTimeMillis();
        for (int i = 0; i < 5; i++) {
            now = System.currentTimeMillis();
            for (int j = 0; j < 100000; j++) {
                int k = i * 100000 + j;
                FuturePosition pos = getFuturePosition(k);
                if (k < 1000) {
                    posList.add(pos);
                }
                ftPositions.add(pos);
            }
            System.err.println("insert 5000000 costs: " + (System.currentTimeMillis() - now));
        }

        now = System.currentTimeMillis();
        for (int j = 0; j < 10000; j++) {
            Query<FuturePosition> query = equal(FuturePosition.INDEX_POS_TRADINGACCOUNT, "tradingaccount" + j);
            ResultSet<FuturePosition> result = ftPositions.retrieve(query);
            // System.out.println(result);
        }
        System.err.println("query 10000 times costs: " + (System.currentTimeMillis() - now));

        now = System.currentTimeMillis();
        for (int i = 0; i < 1000; i++) {
//            ftPositions.remove(posList.get(i));
//            ftPositions.add(posList.get(i));
            ftPositions.update(Arrays.asList(posList.get(i)), Arrays.asList(posList.get(i)));
        }
        System.err.println("update 1000 times costs: " + (System.currentTimeMillis() - now));
    }

    public static FuturePosition getFuturePosition(int i) {
        FuturePosition pos = new FuturePosition();
        pos.setProductaccount("productAccount" + i);
        pos.setAssetaccount("assetaccount" + i);
        pos.setTradingaccount("tradingaccount" + i);
        pos.setSecurityaccount("securityaccount" + i);
        pos.setSecurityid("securityid" + i);
        pos.setInvesttype("investtype" + i);
        pos.setSecurityexchange("M");
        return pos;
    }
}

---------------------------
import java.math.BigDecimal;
import java.util.Date;

import com.googlecode.cqengine.attribute.Attribute;
import com.googlecode.cqengine.attribute.SimpleAttribute;
import com.googlecode.cqengine.query.option.QueryOptions;

public class FuturePosition {
    private String assetaccount;

    private String investtype;

    private String positionflag;

    private String productaccount;

    private String securityaccount;

    private String securityexchange;

    private String securityid;

    private String tradingaccount;

    private BigDecimal holdingqty;

    private BigDecimal newholdingqty;

    private BigDecimal oldholdingqty;

    private BigDecimal holdingcost;

    private BigDecimal opencost;

    private BigDecimal holdingprofit;

    private Date createdate;

    private BigDecimal beginqty;

    private BigDecimal intradayboughtqty;

    private BigDecimal intradaysoldqty;

    private BigDecimal oldholdingpresellqty;

    private BigDecimal newholdingpresellqty;

    private BigDecimal prebuyqty;

    private BigDecimal totalfee;

    public String getAssetaccount() {
        return assetaccount;
    }

    public void setAssetaccount(String assetaccount) {
        this.assetaccount = assetaccount;
    }

    public String getInvesttype() {
        return investtype;
    }

    public void setInvesttype(String investtype) {
        this.investtype = investtype;
    }

    public String getPositionflag() {
        return positionflag;
    }

    public void setPositionflag(String positionflag) {
        this.positionflag = positionflag;
    }

    public String getProductaccount() {
        return productaccount;
    }

    public void setProductaccount(String productaccount) {
        this.productaccount = productaccount;
    }

    public String getSecurityaccount() {
        return securityaccount;
    }

    public void setSecurityaccount(String securityaccount) {
        this.securityaccount = securityaccount;
    }

    public String getSecurityexchange() {
        return securityexchange;
    }

    public void setSecurityexchange(String securityexchange) {
        this.securityexchange = securityexchange;
    }

    public String getSecurityid() {
        return securityid;
    }

    public void setSecurityid(String securityid) {
        this.securityid = securityid;
    }

    public String getTradingaccount() {
        return tradingaccount;
    }

    public void setTradingaccount(String tradingaccount) {
        this.tradingaccount = tradingaccount;
    }

    public BigDecimal getHoldingqty() {
        return holdingqty;
    }

    public void setHoldingqty(BigDecimal holdingqty) {
        this.holdingqty = holdingqty;
    }

    public BigDecimal getNewholdingqty() {
        return newholdingqty;
    }

    public void setNewholdingqty(BigDecimal newholdingqty) {
        this.newholdingqty = newholdingqty;
    }

    public BigDecimal getOldholdingqty() {
        return oldholdingqty;
    }

    public void setOldholdingqty(BigDecimal oldholdingqty) {
        this.oldholdingqty = oldholdingqty;
    }

    public BigDecimal getHoldingcost() {
        return holdingcost;
    }

    public void setHoldingcost(BigDecimal holdingcost) {
        this.holdingcost = holdingcost;
    }

    public BigDecimal getOpencost() {
        return opencost;
    }

    public void setOpencost(BigDecimal opencost) {
        this.opencost = opencost;
    }

    public BigDecimal getHoldingprofit() {
        return holdingprofit;
    }

    public void setHoldingprofit(BigDecimal holdingprofit) {
        this.holdingprofit = holdingprofit;
    }

    public Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public BigDecimal getBeginqty() {
        return beginqty;
    }

    public void setBeginqty(BigDecimal beginqty) {
        this.beginqty = beginqty;
    }

    public BigDecimal getIntradayboughtqty() {
        return intradayboughtqty;
    }

    public void setIntradayboughtqty(BigDecimal intradayboughtqty) {
        this.intradayboughtqty = intradayboughtqty;
    }

    public BigDecimal getIntradaysoldqty() {
        return intradaysoldqty;
    }

    public void setIntradaysoldqty(BigDecimal intradaysoldqty) {
        this.intradaysoldqty = intradaysoldqty;
    }

    public BigDecimal getOldholdingpresellqty() {
        return oldholdingpresellqty;
    }

    public void setOldholdingpresellqty(BigDecimal oldholdingpresellqty) {
        this.oldholdingpresellqty = oldholdingpresellqty;
    }

    public BigDecimal getNewholdingpresellqty() {
        return newholdingpresellqty;
    }

    public void setNewholdingpresellqty(BigDecimal newholdingpresellqty) {
        this.newholdingpresellqty = newholdingpresellqty;
    }

    public BigDecimal getPrebuyqty() {
        return prebuyqty;
    }

    public void setPrebuyqty(BigDecimal prebuyqty) {
        this.prebuyqty = prebuyqty;
    }

    public BigDecimal getTotalfee() {
        return totalfee;
    }

    public void setTotalfee(BigDecimal totalfee) {
        this.totalfee = totalfee;
    }

    public String getFuturePositionKey() {
        StringBuilder bld = new StringBuilder();
        return bld.append(productaccount).append(assetaccount).append(tradingaccount).append(securityaccount)
                .append(investtype).append(securityexchange).append(securityid).append(positionflag).toString();
    }

    public static final Attribute<FuturePosition, String> INDEX_POS_ASSETACCOUNT = new SimpleAttribute<FuturePosition, String>(
            "posAssetAccount") {
        @Override
        public String getValue(FuturePosition object, QueryOptions queryOptions) {
            return object.getAssetaccount();
        }
    };

    public static final Attribute<FuturePosition, String> INDEX_POS_TRADINGACCOUNT = new SimpleAttribute<FuturePosition, String>(
            "posTradingAccount") {
        @Override
        public String getValue(FuturePosition object, QueryOptions queryOptions) {
            return object.getTradingaccount();
        }
    };

    public static final Attribute<FuturePosition, String> INDEX_POS_UNIQUE = new SimpleAttribute<FuturePosition, String>(
            "posPirmaryKey") {
        @Override
        public String getValue(FuturePosition object, QueryOptions queryOptions) {
            return object.getFuturePositionKey();
        }
    };

    public static final Attribute<FuturePosition, String> INDEX_POS_SECURITY = new SimpleAttribute<FuturePosition, String>(
            "posSecurity") {
        @Override
        public String getValue(FuturePosition object, QueryOptions queryOptions) {
            return getSecurityInfo(object.getSecurityexchange(), object.getSecurityid());
        }
    };

    private static String getSecurityInfo(String securityExchange, String securityId) {
        return securityId + "." + securityExchange;
    }
}

------------
result:
insert 100000 costs: 2241
insert 100000 costs: 757
insert 100000 costs: 2370
insert 100000 costs: 3924
insert 100000 costs: 3678
query 10000 times costs: 53
update 1000 times costs: 51348

------------
I found the time was mainly cost at CollectionWrappingObjectStore:
    @Override
    public boolean removeAll(Collection<?> c, QueryOptions queryOptions) {
        boolean f = backingCollection.removeAll(c);
        return f;
    }

and if I modify it as follows:
    @Override
    public boolean removeAll(Collection<?> c, QueryOptions queryOptions) {
        Iterator<?> it = c.iterator();
        while(it.hasNext()){
            backingCollection.remove(it.next());
        }
//        boolean f = backingCollection.removeAll(c);
        return true;
    }

above test's result:
-----------------------------
insert 100000 costs: 2453
insert 100000 costs: 749
insert 100000 costs: 2309
insert 100000 costs: 3998
insert 100000 costs: 577
query 10000 times costs: 54
update 1000 times costs: 24

However, I am afraid that  this modification may result in other question. Could I do this?

**Comment by npgall** [comment]
This sounds interesting. Certainly this sounds like an unusual bottleneck. I did not get time to actually run this code today, but I will try to investigate a bit further tomorrow.

**Comment by npgall** [comment]
Thanks for reporting this. 

It's actually due to a performance bottleneck in ConcurrentHashMap in the JDK, which basically may occur when CQEngine is run on Java 8 or earlier. The issue would not occur if CQEngine was run on Java 9. You can see [JDK-8160751](https://bugs.openjdk.java.net/browse/JDK-8160751) for details.

I've added a workaround to CQEngine which avoids calling the problematic code. It fixes the strange performance issue you reported. I'll release a point release of CQEngine tonight which includes it.

Many thanks for reporting this!
