### ISSUE TITLE
kryo dependency out of date

### ISSUE THREAD

**Issue by bluedoo** [npgall/cqengine#159]
cqengine is heavily dependent on kryo and with jdk9 it may become unusable, see: https://github.com/magro/kryo-serializers/issues/71

**Comment by npgall** [comment]
Good point bluedoo. I will update to a newer version of Kryo in the next release.

**Comment by npgall** [comment]
Hi bluedoo,
Kryo is now upgraded to the latest version in mainline, and will be included in CQEngine 3.x which is the next release. CQEngine 3.x will focus on Java 9 compatibility (and drop compatibility with Java 6 & 7).
