### ISSUE TITLE
kotlin LambdaAttributes compatibility

### ISSUE THREAD

**Issue by zdevwu** [npgall/cqengine#166]
I had a solved issue, just post here for someone using Kotlin.

When using QueryFactory.attribute(Foo::bar) to generate SimpleAttribute. The underlying call to TypeResolver.resolveRawArguments couldn't extract the type information from kotlin generated function call. A helper inline method gives you the same simple oneliner:
```
inline fun <reified O, reified A> attribute(accessor: KProperty1<O, A>): FunctionalSimpleAttribute<O, A> {
    return FunctionalSimpleAttribute(O::class.java, A::class.java, accessor.javaClass.simpleName, SimpleFunction { accessor.get(it) })
}

// then you can use:
class Foo(
    val bar: Int
) {
    companion object {
        val BAR = attribute(Foo::bar)
    }
}
```

**Comment by npgall** [comment]
Hi zdevwu,

That's a great tip, many thanks!

I just added a [new wiki page](https://github.com/npgall/cqengine/blob/master/documentation/OtherJVMLanguages.md) about using CQEngine with other languages such as Kotlin and Scala.

I added your example above to a section for Kotlin.

If you have any more tips, let me know. You can either create additional issues, or submit a PR to add new details to the new wiki page.

Many thanks!
