### ISSUE TITLE
Concurrent off-heap indexed collection creation issues with sqlite-jdbc 

### ISSUE THREAD

**Issue by imonteroperez** [npgall/cqengine#169]
Hi Niall,

Seems that when we want to create some off-heap based indexed collections in concurrent scenarios, current version of sqlite-jdbc used on cqengine goes to a race condition on NativeBD open method:

java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V

Fix for this issue has been included here:
https://github.com/niktsar/sqlite-jdbc/commit/69a5741c7cb6e2e3cd5e21f6bd748b7323ffce32

So, maybe would be a great idea to change version of this dependency in pom.xml to 3.20.1 instead of current 3.16.1. I'm currently testing an own cqengine fork with this updated version without issues (at the moment).

**Comment by imonteroperez** [comment]
I have just created a PR about this here: https://github.com/npgall/cqengine/pull/170

**Comment by npgall** [comment]
Hi Ildefonso, 

I wasn't aware of that issue, thanks for reporting it!

I do plan to upgrade to the latest versions of most dependencies including sqlite-jdbc 3.20.1 for the next major release 3.x. I'm doing development for that release in a branch [incubating-3.0](https://github.com/npgall/cqengine/tree/incubating-3.0) until it's ready to merge.

I can confirm that CQEngine works perfectly with sqlite-jdbc 3.20.1 though, and all of CQEngine's tests pass with it. So it should be fine to use CQEngine 2.12.x with sqlite-jdbc 3.20.1 in the meantime as a workaround if you wish.

Anyway I will keep this issue open until the next release is ready, in case other people are affected by that UnsatisfiedLinkError too, and might want to explicitly use the newer version of sqlite-jdbc as a workaround in the meantime. 

Thanks for taking time to investigate this!

**Comment by imonteroperez** [comment]
Great!

Thanks to you for this awesome project :-)

**Comment by npgall** [comment]
CQEngine has finally been released, now using sqlite-jdbc 3.23.1. So this issue should be resolved. Sorry for the delay!

**Comment by imonteroperez** [comment]
I solved the conflicts of the PR attached to this issue, due to I proposed 3.20.1 and you tested with 3.23.1 without issues :-)
