### ISSUE TITLE
Can we put two equal check in my CQ engine query

### ISSUE THREAD

**Issue by jasgeeteden** [npgall/cqengine#176]
Like this,

Query<OrderBook> query =  and( equal(OrderBook.ORDER_STATUS,OrderStatus.OPEN.toString()), equal(OrderBook.CLIENT, order.getClientId()));

 because I am not getting any result from this query, though I have checked twice in Collection , We have the entries so result should come.

**Comment by npgall** [comment]
Yes that's a fairly standard requirement, and it's well tested and confirmed to be supported.

My guess is there's something strange going on in your data. Could you provide a standalone test case which reproduces the problem?

**Comment by jasgeeteden** [comment]
it is working now
