### ISSUE TITLE
[question] Is it possible to apply filtering/querying to a streaming input collection?

### ISSUE THREAD

**Issue by josdejong** [npgall/cqengine#179]
I have a stream of objects (POJO's) coming in from an external source, and need to have a way to filter this stream using a (dynamic) query language. I would love to use an SQL like language for this, and cqengine looks like a great match in that regard.

As far as I can see, cqengine takes a static collection with data, and query on that: 

```java
    SQLParser<Car> parser
            = SQLParser.forPojoWithAttributes(Car.class, createAttributes(Car.class));
    IndexedCollection<Car> cars = new ConcurrentIndexedCollection<Car>();
    cars.addAll(CarFactory.createCollectionOfCars(10));

    ResultSet<Car> results = parser.retrieve(cars, "SELECT * FROM cars WHERE (" +
                                    "(manufacturer = 'Ford' OR manufacturer = 'Honda'));
```

Is it possible to execute SQL statements against a stream of input data instead? Something like:

```java
    SQLParser<Car> parser
            = SQLParser.forPojoWithAttributes(Car.class, createAttributes(Car.class));

    // Input stream here instead of static data
    Stream<Car> cars = externalSource.fetchCars();

    Stream<Car> results = parser.retrieve(cars, "SELECT * FROM cars WHERE (" +
                                    "(manufacturer = 'Ford' OR manufacturer = 'Honda'));
```

Or, without streaming api, is there a way to match one `Car` entry against a query to see whether it matches? Something like:

```java
boolean isMatch = parser.match(car, "SELECT * FROM cars WHERE (" +
                                    "(manufacturer = 'Ford' OR manufacturer = 'Honda'));
```

In that case I could embed this matching inside the stream and use it for filtering.

**Comment by npgall** [comment]
Hi josdejong,

Yes. This is a good question.

I've just checked in some utility methods which can help with that, which will be released with CQEngine 3.x. You can [copy & paste](https://github.com/npgall/cqengine/blob/1474357bc1f556e36bb3485dd49ded343bcf8743/code/src/main/java/com/googlecode/cqengine/query/QueryFactory.java#L1303) them into your application for now, so you can use them with CQEngine 2.x as long as you are using Java 8.

Usage is as follows:

```java
// Create SQLParser as normal...
SQLParser<Car> parser = SQLParser.forPojoWithAttributes(Car.class, AttributeBytecodeGenerator.createAttributes(Car.class));

// Obtain a stream of objects (cars in this case)...
Stream<Car> carStream = CarFactory.createCollectionOfCars(10).stream();

// Parse the SQL query into a Query object...
Query<Car> query = parser.parse("SELECT * FROM cars WHERE (color = 'BLUE' AND price > 8600.0)").getQuery();

// Convert the Query object to a Predicate...
Predicate<Car> predicate = QueryFactory.predicate(query);

// Use the Predicate to filter the stream...
carStream.filter(predicate).forEach(System.out::println); // Prints: BMW M6
```

**Comment by josdejong** [comment]
wow, that's *exactly* what I'm looking for! Thanks for your fast reply. 

I hope to play around with it coming Monday.

**Comment by josdejong** [comment]
This solution works like a charm! I also experimented with JXPath but that's much slower.

Just for reference, this is what I ended up with:

```java
// Create SQLParser as normal...
SQLParser<Car> parser = SQLParser.forPojoWithAttributes(Car.class,
        AttributeBytecodeGenerator.createAttributes(Car.class));

// Parse the SQL query into a Query object...
String q = "SELECT * FROM cars WHERE (color = 'BLUE' AND price > 8600.0)";
Query<Car> query = parser.parse(q).getQuery();

// Convert the Query object to a Predicate...
Predicate<Car> predicate = object -> query.matches(object, null);

// Use the Predicate to filter the stream...
Stream<Car> cars = ... ;
List<Car> matchingCars = cars
        .filter(predicate)
        .collect(Collectors.toList());
```

I had to add the following dependencies to my `pom.xml` to get it working:
```xml
  <dependencies>
    ...

    <!-- https://mvnrepository.com/artifact/com.googlecode.cqengine/cqengine -->
    <dependency>
      <groupId>com.googlecode.cqengine</groupId>
      <artifactId>cqengine</artifactId>
      <version>2.12.4</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.antlr/antlr4 -->
    <dependency>
      <groupId>org.antlr</groupId>
      <artifactId>antlr4</artifactId>
      <version>4.5</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.antlr/antlr4-runtime -->
    <dependency>
      <groupId>org.antlr</groupId>
      <artifactId>antlr4-runtime</artifactId>
      <version>4.5</version>
    </dependency>

  </dependencies>
```
I'm not sure why I had to define `antlr4` since that's a dependency of `cqengine` but well...

Thanks again.

**Comment by npgall** [comment]
That's a really neat and concise way to convert a Query to a Predicate!
It almost makes me wonder if it was beneficial for me to add those QueryFactory.predicate() methods :) I'll leave them in anyway.

Glad to help! Best of luck with the project.
