### ISSUE TITLE
[request] Support ResultSetIterator to get Streams from ResultSet

### ISSUE THREAD

**Issue by archenroot** [npgall/cqengine#184]
It might be useful in some cases to get Java streams from ResultSet. What about implementing something like this to extend ResultSet?
```

 public static <T> Stream<T> iteratorToStream(final Iterator<T> iterator, final boolean parallell) {
        Iterable<T> iterable = () -> iterator;
        return StreamSupport.stream(iterable.spliterator(), parallell);
    }
```

Maybe better to implement it in form of method .stream directly from ResultSet, any comments welcomed.

**Comment by npgall** [comment]
This is planned in the CQEngine 3.x release. The 3.x version is currently under development in the [incubating-3.0](https://github.com/npgall/cqengine/tree/incubating-3.0) branch.

Watch this space!
