### ISSUE TITLE
Java stream

### ISSUE THREAD

**Issue by tokazio** [npgall/cqengine#186]
Hi,

this is an enhancement request,

Have you plan to implements java stream with cqengine backend?

For example, instead of
`IndexedCollection.retrieve(startsWith(DESIGNATION, "DOLI")).stream().forEach(System.out::println);`

Have
`IndexedCollection.stream().filter(DESIGNATION.startsWith("DOLI")).forEach(System.out::println);`

**Comment by npgall** [comment]
Yes this is planned. You can find some details in #184

**Comment by archenroot** [comment]
#184

**Comment by npgall** [comment]
This is now available in CQEngine 3.x :)
