### ISSUE TITLE
Searching/filtering/paging with off-heap indexes and collections

### ISSUE THREAD

**Issue by klehmann** [npgall/cqengine#190]
In my application, I am using CQEngine with several off-heap indexes and an off-heap collection.
I need to query data with multiple search criteria and sort the results. The result is then displayed in a web app with paging.

When I understand CQEngine correctly, this produces lots of object deserialization between Sqlite and Java to compute the result, when a lot of objects match a query, because all needs to be materialized in order to get sorted.
According to the documentation, I can use an index for sorting, but then no other indexes are used for the lookup.

Is this correct? Is there no way to combine an off-heap indexed based search with an off-heap index based sorting, using just the primary keys of the objects, followed by a lazy-deserialization that only processes the objects of a requested page?

If there is currently no way, what is the recommended way to speed up my scenario? Use an on-heap collection with off-heap indexes so that objects do not have to get deserialized?

**Comment by klehmann** [comment]
No yet. Will this work when data needs to be sorted? Should I create an index that matches the required sorting(s)?
For even better performance, a skip method on the final collection iterator would be great that skips multiple collection entries without deserializing them.

**Comment by npgall** [comment]
Closing this, because I believe what you want, should already be supported by the [index merge strategy](https://github.com/npgall/cqengine/blob/master/documentation/MergeStrategies.md), or the [index accelerated ordering](https://github.com/npgall/cqengine/blob/master/documentation/OrderingStrategies.md) strategy. Feel free to reopen if that's not the case.
