### ISSUE TITLE
Be able match enum fields with SQL patterns LIKE and IN

### ISSUE THREAD

**Issue by josdejong** [npgall/cqengine#197]
It looks like it is not possible to match fields which are an enum using SQL statements `LIKE` and `IN` like we can do with text fields. It looks like enums can only be exact matches with `=`, but maybe I'm overlooking something here.

Say we have a car POJO which as a `type` fields which is an enum, I would like to be able to query like:
```
SELECT * FROM cars WHERE type IN ('CABRIO', 'SMALL_TRUCK', 'LARGE_TRUCK')
SELECT * FROM cars WHERE type LIKE '%TRUCK'
```
Is there a way to do this with enums?

**Comment by npgall** [comment]
Yes, you should be able to do this. 

SQL the language doesn't understand Java enums, but it does understand collections of strings. So what you can do, is define a CQEngine virtual attribute, which reads the enum value from your object, and converts it to a String. This will then be accessible in SQL queries.

Something like this should work, we use a lambda to do the conversion:
```java
SimpleAttribute<Car, String> TYPE = attribute("type", car -> car.type.toString());
```

Hope that helps!
Niall

**Comment by josdejong** [comment]
It is a while ago, I did some testing again, seems that `IN` just works out of the box for enums, only `LIKE` not. Thanks for your suggestion of converting enums into strings on the fly.
