### ISSUE TITLE
NPE with nullable attribute

### ISSUE THREAD

**Issue by brettwooldridge** [npgall/cqengine#202]
The exception I am getting is:
```
java.lang.NullPointerException: null
	at com.googlecode.cqengine.query.simple.Equal.calcHashCode(Equal.java:78) ~[cqengine-2.12.4.jar:?]
	at com.googlecode.cqengine.query.simple.SimpleQuery.hashCode(SimpleQuery.java:103) ~[cqengine-2.12.4.jar:?]
	at java.util.AbstractList.hashCode(AbstractList.java:541) ~[?:1.8.0_161]
	at com.googlecode.cqengine.query.logical.And.calcHashCode(And.java:77) ~[cqengine-2.12.4.jar:?]
	at com.googlecode.cqengine.query.logical.LogicalQuery.hashCode(LogicalQuery.java:120) ~[cqengine-2.12.4.jar:?]
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_161]
	at com.googlecode.cqengine.engine.CollectionQueryEngine.retrieveRecursive(CollectionQueryEngine.java:892) ~[cqengine-2.12.4.jar:?]
	at com.googlecode.cqengine.engine.CollectionQueryEngine.retrieveWithoutIndexOrdering(CollectionQueryEngine.java:495) ~[cqengine-2.12.4.jar:?]
	at com.googlecode.cqengine.engine.CollectionQueryEngine.retrieve(CollectionQueryEngine.java:473) ~[cqengine-2.12.4.jar:?]
	at com.googlecode.cqengine.ConcurrentIndexedCollection.retrieve(ConcurrentIndexedCollection.java:110) ~[cqengine-2.12.4.jar:?]
	at dancer.provider.incidents.internal.ViolationScoreboard.findActiveEventsForMeasurement(ViolationScoreboard.kt:244) ~[com-dancer-provider-incidents.jar:?]
```

This nullable attribute in question is a ``String``, with the attribute defined as:
```
MEASUREMENT_INDEX = cqNullableAttribute(TriggerEvent::measurementIndex)
```
Not that it matters, but the ``cqNullableAttribute()`` function is a Kotlin function defined as:
```kotlin
inline fun <reified O, reified A> cqNullableAttribute(accessor: KProperty1<O, A>): FunctionalSimpleNullableAttribute<O, A> =
   FunctionalSimpleNullableAttribute(O::class.java, A::class.java, accessor.javaClass.simpleName, SimpleFunction { accessor.get(it) })
```
The query in question is:
```kotlin
val measurementQuery: Query<TriggerEvent> =
   and(
      equal(TriggerEvent.HOST_UUID, hostUuid),
      equal(TriggerEvent.NETWORK, network),
      equal(TriggerEvent.MEASUREMENT, measurement),
      equal(TriggerEvent.MEASUREMENT_INDEX, measurementIndex),
      equal(TriggerEvent.TRIGGER_ID, triggerId),
      not(
         equal(TriggerEvent.CLEARED, TriggerClearState.CLEARED)
      )
   )
```
Where ``measurementIndex`` *is* ``null`` in the failing query.

**Comment by brettwooldridge** [comment]
This is the point of the exception, in ``Equal.java``:
```java
@Override
protected int calcHashCode() {
    int result = attribute.hashCode();
    result = 31 * result + value.hashCode();
    return result;
}
```
I don't know if adding:
```java
 if (attribute == null) return 0;
```
to the method is an appropriate fix or not, or whether it should be handled higher up?  If this *is* the appropriate location, then a similar change needs to be made to all the operators.

**Comment by npgall** [comment]
Re: "Not that it matters, but the cqNullableAttribute() function is a Kotlin function"

It might well matter, as this issue doesn't occur in Java right?

There is no point in adding special handling to allow a null attribute to be supplied to a query. Attributes are the things which are examined by queries. The proper solution is to ensure that a non-null attribute gets passed to the constructor of the query.

I am not very familiar with Kotlin, but that said I'd like to facilitate CQEngine working with it and there is a FAQ on this in [OtherJVMLanguages.md](https://github.com/npgall/cqengine/blob/master/documentation/OtherJVMLanguages.md). However
I note your attribute seems to be defined in accordance with the example in that FAQ, which was provided by another user who had used CQEngine with Kotlin successfully.

I think there must be something strange going on with how the query or the attribute is defined in Kotlin. What makes MEASUREMENT_INDEX (which doesn't work) different from MEASUREMENT (which does work) in your application? Does it have a different data type or something? I think this needs more investigation on your end.

**Comment by brettwooldridge** [comment]
Thanks for the reply.  I’ll dig a little deeper and if it still appears to be a cqEngine issue will produce a compact test case.

**Comment by patric-r** [comment]
We have a similar issue here. Consider the query fragment     
`or(not(has(Part.TYPE)), equal(Part.TYPE, p.getType())))`

because `or` doesn't short-circuit, it will always resolve the equals part which will fail with a NPE despite the fact the attribute has been declared as nullable:

```
Exception in thread "main" java.lang.NullPointerException
	at com.googlecode.cqengine.query.simple.Equal.calcHashCode(Equal.java:78)
	at com.googlecode.cqengine.query.simple.SimpleQuery.hashCode(SimpleQuery.java:103)
	at java.util.AbstractList.hashCode(AbstractList.java:541)
	at com.googlecode.cqengine.query.logical.Or.calcHashCode(Or.java:107)
	at com.googlecode.cqengine.query.logical.LogicalQuery.hashCode(LogicalQuery.java:120)
```

**Comment by npgall** [comment]
Again, the attribute object which is passed to a query should never be null. 

The has() query does not check if the attribute object passed to it is not null. It invokes the attribute object, and checks if the attribute provides any values.

The stack trace above implies the attribute passed to a query was indeed null though.

How can this happen? I assume it is some weird behavior with Kotlin.

I think you'll need to investigate further on your end, or provide the simplest possible test case which I can run which reproduces the problem.

**Comment by patric-r** [comment]
Nope, the `Attribute `object (which is, in my case `PART.TYPE`) is **not** null but it's defined as a nullable attribute. In my case above, there are some objects in the collection which values are indeed null for this attribute.

I'll try providing a minimalistic test case.

BTW: I'm using pure java 8 (no Kotlin involved).

**Comment by patric-r** [comment]
Yes, the value which I'm supplying is indeed null. 
But I thought that this is what "nullable attributes" are for..

How can I archive matching an attribute which can be optional for both within the collection and query supply?

**Comment by npgall** [comment]
The has() query will match objects which have values for an attribute (this is the equivalent of IS NOT NULL in SQL), and so you can use not(has()) as the equivalent of IS NULL in SQL.

In SQL you need to use a dedicated query to check for nulls, and the same applies with CQEngine.

So if you want a query which matches objects which have null fields, you can use a nullable attribute, and then use a 'not(has(attribute))' query.

Hope that helps,
Niall
