### ISSUE TITLE
Transactional Rollback

### ISSUE THREAD

**Issue by buko** [npgall/cqengine#204]
I would like to be able to operate on an IndexedCollection in a transactional matter. The workflow would be something like:

- Begin Transaction
- Update the index. (Add some object to the IndexedCollection or remove an object.)
- Update the index.
- Rollback

Is there an efficient way to do this with IndexedCollections backed by DiskPerformance? It seems like CQEngine uses SQLite under the covers... would it be possible to access the underlying transactional machinery here?

The alternative is to simply undo the updates. Would each undo start a new transaction?

I also wonder what the actual transactional behavior of CQEngine is? Does CQEngine use transactions against SQLite? Is there a way to batch updates and transactionally update (or rollback) a group of Indexes at once?

**Comment by npgall** [comment]
There is no support to explicitly rollback transactions I'm afraid.

Although CQEngine uses SQLite behind the scenes, SQLite is only used by some of the indexes. Additionally, it's possible that CQEngine might use multiple instances of SQLite (e.g. one for disk and one for off-heap persistence) in the same IndexedCollection instance at the same time, besides any non SQLite indexes. So the difficulty of coordinating rollback-able transactions across different persistence mechanisms would be too high.

To answer your other question - CQEngine's own transactions do not depend on SQLite transactions. CQEngine coincidentally does use SQLite transactions under the hood, but it's mainly as a way to batch multiple IO operations together for performance reasons only. The CQEngine transactions do not depend on SQLite, they work across Java based indexes too.

Currently transactions in CQEngine (via TransactionalIndexedCollection) exist to provide atomicity in multi-threaded situations, not to support rollback per-se.

**Comment by buko** [comment]
Thanks for the answer @npgall . That explains a lot. I spent some time looking at TransactionalIndexedCollection but it didn't seem to be what we needed.

Do you have any ideas how we might support rollbacks in an efficient manner?

We would like to disk-based IndexedCollections and Indexes to reduce RAM usage. Our CQEngines are aware of what's happening with the current transaction and implement the TransactionParticipant interface.  The simplest mechanism would be to (a) on each event from the current transaction update the index and then, if the transaction rolls back, undo the effects of the event to the indexes via compensating operations. This will work but it will also, I worry, lead to unnecessary I/O. Even if we can't rollback CQEngine operations in a transactional manner, is there a way to delay I/O to disk until we can be sure that the transaction has committed?

**Comment by npgall** [comment]
I'm afraid there is no out-of-the-box support for delaying the commit of disk IO operations.

If you can achieve what you need using compensating transactions in your application that's probably the best way to go.
