### ISSUE TITLE
In SQL, filter is not working properly if filter value contains single quote( ' ).

### ISSUE THREAD

**Issue by vj126** [npgall/cqengine#207]
In SQL, consider the following example:
`SELECT * FROM CAR WHERE ( 'name' = 'Sam''s car' )`
Where the filter attribute is `name` and filter value is `Sam's car`. (Extra single quote is used as escape character.)
It is obeserved that
1) If value of attribute `name` is `Sam's car` in actual data, above filter does not return this data.
1) If value of attribute `name` is `Sam''s car` in actual data, above filter returns this data.

**Comment by npgall** [comment]
Thanks for reporting this! This is now fixed.
