### ISSUE TITLE
Add support for dropping indexes

### ISSUE THREAD

**Issue by venustus** [npgall/cqengine#208]
Today, we can create indexes on collections, but there is no way (that I can see from the API) to drop them. This feature is not probably a big deal for regular applications (like the CAR example), but in our application, we create attributes and indexes programmatically based on query patterns and our application can have many many fields (say hundreds) within objects. 

So, when I want to update an object using `collection.update` just because one of those hundreds of fields has changed, CQEngine ends up updating indexes on all other fields as well (in my understanding), when nothing changed in those fields. I would like to improve the update performance by proactively dropping unused indexes. Of course, any additional memory gains would be a bonus.

**Comment by venustus** [comment]
Wanted to add that this is useful not just in the context of performance improvement, but it is also necessary to support any use case where field set of an object is dynamic. If I remove a field from an object, the queries referring to that field will continue to return objects which matched with the query when the field was present. This is not a problem if the list of fields in an object is static, but since we can create and add attributes and indexes on-the-fly and we can use accessor functions to define attributes, it is not unimaginable to have a dynamic list of fields which may be added or deleted while the application is running. 

More problematic is the situation when field is deleted and then added back with same name after some time. Since the corresponding CQEngine index on that attribute has always been present and never got dropped, any query referring to this field will start returning spurious objects (which may not contain the value being searched for, right now).

**Comment by npgall** [comment]
An `IndexedCollection.removeIndex()` method is now implemented.
This will be included in the next release, ETA next few days.
