### ISSUE TITLE
Add ability to update specific indexes directly

### ISSUE THREAD

**Issue by venustus** [npgall/cqengine#210]
I know it has been discussed on many occasions about perils of putting mutable objects into indexed collections (or any Java collections for that matter). General approach to deal with mutating objects that were added to collection is to remove that object and add the mutated object back.

But removing and adding it back is expensive when there are many fields. If we have tight control on which fields have changed in a particular mutation it should be possible for a consumer of CQ Engine to explicitly update only the affected indexes. The most common scenario here, is when a field of an object changed where that field is not involved in generating the hash code of the object itself, but is used in one or two indexes as the key field. 

Then, it doesn't make sense to remove the object and add the same again to collection triggering index updates on all fields. It makes more sense for the consumer to just mutate the object and call a specific method to update the affected indexes.

**Comment by npgall** [comment]
I'm afraid it's just too hard and not always feasible to do this.

Although CQEngine attributes _typically_ are programmed to read fields in objects, attributes are actually functions and CQEngine doesn't really know where the data comes from. 

Attributes can be programmed to read from multiple fields and combine them using some kind of function, they can calculate a value by applying some formula, or they can fetch data _relating_ to the object from some external system instead.

Consider a case where there's an attribute which computes its value by applying a formula to one or more fields in an object. 

```java
class Car {

int yearOfManufacture;

public static final Attribute<Car, Boolean> CAR_AGE = attribute(car -> getCurrentYear() - car.yearOfManufacture);
}
```
In this case if the yearOfManufacture field was changed, it would be difficult for CQEngine to know which attributes' values would change as a result.

Hope that helps,
Niall

**Comment by Rubyjunk** [comment]
Could this issue not be mitigated by a manual index update: e.g.

```java
collection.updateIndexesOn(Car.CAR_AGE);
```

that updates every index watching this particular attribute?
