### ISSUE TITLE
In SQL, filtering is not working on negative numbers.

### ISSUE THREAD

**Issue by vj126** [npgall/cqengine#213]
In SQL, filtering on negative numbers throws the following exception:

> Exception in thread "main" com.googlecode.cqengine.query.parser.common.InvalidQueryException: Failed to parse query at line 1:39: no viable alternative at input '( column1 = -'

For query: `SELECT * FROM table1 WHERE ( column1 = -5 )`

**Comment by nivs** [comment]
+1

**Comment by npgall** [comment]
I will try to get to this soon. In the meantime, you could expedite this by submitting a Pull Request! 😄 The SQL parsing is fairly self-contained.

**Comment by npgall** [comment]
This is now fixed.
