### ISSUE TITLE
ResultSet iterator not working properly on fetching next element with SuffixTreeIndex

### ISSUE THREAD

**Issue by zubair-farooqui** [npgall/cqengine#217]
I am using ConcurrentIndexedCollection with SuffixTreeIndex on attribute. When I use contains query on collection then it returns ResultSet which has X number of records. When I use iterator provided by ResultSet and call next() to get next element then it throws "java.util.NoSuchElementException: No more elements".  However, it is working fine on forEach on ResultSet. I am using 2.12.4 version of CQEngine

![image](https://user-images.githubusercontent.com/12321796/48935959-31076300-ef2b-11e8-9e6d-d93ce29659dc.png)

**Comment by npgall** [comment]
Could you provide a standalone test case which I can run to reproduce this?

**Comment by npgall** [comment]
I will close this now, as there was not enough information provided for me to investigate. Feel free to reopen if you can provide a reproducer. Thanks!
