### ISSUE TITLE
Equal() should check for null value on construction

### ISSUE THREAD

**Issue by adamsantos67** [npgall/cqengine#223]
I just ran into issue #202 yesterday. We had some existing code that was using Equal to check for null that was working until I made a change to an index type. Apparently before, the code never accessed calcHashCode() and never threw an NPE. I see that Equal's parent class, SimpleQuery, throws an IllegalArgumentException in its constructor if attribute is null. Equal should do the same if value is null. 

Other related classes like LessThan and GreaterThan should also check for a null value.

**Comment by npgall** [comment]
That makes sense. I have added the null checking per your suggestion. It's added to all queries. Thanks!
