### ISSUE TITLE
QEngine has seamless integration with JPA/ORM frameworks such as Hibernate or EclipseLink.

### ISSUE THREAD

**Issue by muhdkhokhar** [npgall/cqengine#224]
You have this in readme  QEngine has seamless integration with JPA/ORM frameworks such as Hibernate or EclipseLink.

I cannot find way to integrate with jpa

**Comment by npgall** [comment]
```java
List<MyEntity> entities = // load list of entity objects from JPA/ORM framework

IndexedCollection<MyEntity> indexedCollection = new ConcurrentIndexedCollection();

indexedCollection.addAll(entities);
```

**Comment by muhdkhokhar** [comment]
What about crud ops??

**Comment by npgall** [comment]
Just to be clear, CQEngine won't create/retrieve/update or delete objects in your database. You need to use your ORM framework for that. But you can load objects from an ORM framework into a CQEngine IndexedCollection, and then query the IndexedCollection locally without accessing the database.

Hope that helps,
Niall

**Comment by muhdkhokhar** [comment]
I get that part. I mean can I not update the entry in the collection once its inserted. 

I want to write a service wrapper top of JPA that will use cqegine. When I call save I'll update DB and if succesful I update the entry in CQEngine. This way it will be in sync and utlize quick queries and sort of caching.

**Comment by npgall** [comment]
I see how that would be useful, but I'm afraid that is not supported. CQEngine currently works beside ORM frameworks, but not really "underneath" or "above" them.

This is not something that I'd like to integrate into CQEngine's core as it would be a huge undertaking with a lot of complexity, and I wouldn't like to couple CQEngine with any particular ORM framework. However I'd support anyone else who wants to start a separate open source project to integrate CQEngine "underneath" or "above" an ORM framework like that :)

I'll close this. In future if someone wants to tackle that in a separate open source project, I'd be happy to help out if I can.
