### ISSUE TITLE
Just a note ...

### ISSUE THREAD

**Issue by nschlimm** [npgall/cqengine#225]
hey @npgall 
found no other better way to get in contact. wrote [this little library](https://github.com/projectbarbel/barbelhisto-core) for bi-temporal data management based on cqengine ! appreciate any comments from you, and many thanks for your excellent work!
(you can delete this issue, its not meant as marketing move :-)) 
regards,
niklas

**Comment by npgall** [comment]
I took a look at barbelhisto -- very nice!!

I have been meaning to put together a wiki page of "projects using or used by CQEngine". When I get a chance I will include barbelhisto, thanks!

Let me know if you need anything from CQEngine for barbelhisto. I work on CQEngine sporadically and in bursts so next time I could look at that in more detail.

Nice work!
