### ISSUE TITLE
DiskPersistence

### ISSUE THREAD

**Issue by nschlimm** [npgall/cqengine#226]
Hi Niall,
is there a way to find about, later in the process, if a collection is persistent or not? I want to validate if users pass correctly configured objects, but that also depends on whether or not the collection is configured with DiskPersistence. Any advice?
Regards Niklas

**Comment by npgall** [comment]
Good question. Not currently. But I have just implemented such a method `IndexedCollection.getPersistence()`, and it will be included in the next release.

In the meantime, a partial workaround is to call `collection.getIndexes()`, and check if any of the indexes are of type `SQLiteIdentityIndex` - this will be used by both disk and off-heap persistence; but not by on-heap persistence.
