### ISSUE TITLE
Dependency inconsistency

### ISSUE THREAD

**Issue by peter-ryan** [npgall/cqengine#228]
The dependency chain for cqengine misrepresents the proper kyro version. Using the enforcer plugin in maven there are two version of kyro it is trying to pull in. Can this be made more explicit?

Dependency convergence error for com.esotericsoftware:kryo:5.0.0-RC1 paths to dependency are:
  +-com.googlecode.cqengine:cqengine:3.0.0
    +-com.esotericsoftware:kryo:5.0.0-RC1
and
  +-com.googlecode.cqengine:cqengine:3.0.0
    +-de.javakaffee:kryo-serializers:0.42
      +-com.esotericsoftware:kryo:4.0.0

**Comment by npgall** [comment]
This should be fixed in CQEngine 3.2.0 just released. Please reopen if you still have issues with that version. Thanks!
