### ISSUE TITLE
ResultSet collect takes a lot of time

### ISSUE THREAD

**Issue by 0top** [npgall/cqengine#234]
I noticed when I got the resultSet and then run the following code:
```
ResultSet result= datas.retrieve(v1, queryOptions);
result.stream().collect(Collectors.toList());
```
This operation takes a long time when the size of datas is  20,000。
Can this operation be optimized?
thanks。

**Comment by npgall** [comment]
With your question above, it's like asking "my database is slow, what can I do?". There's not enough detail in that question for anyone to help. You'll need to provide a lot more detail. 

For example, there's a lot of information on the site about how to tune query performance. Especially by adding indexes. Have you read the documentation, and what kinds of indexes and queries are you using? What were your findings etc.?

I will close this for now for the reason above. Feel free to reopen if you could include more details.
