### ISSUE TITLE
Grouping and Aggregation support like pure SQL

### ISSUE THREAD

**Issue by CptGuo** [npgall/cqengine#236]
Hi, thank to support this tool, it's so good to solve my problem, but there's a bit problem to me.

My require is define CQENGINE QUERY string first and then execute it like MyBatis definition xml, but it's can't define group and aggregation in CQEGINE QUERY string.
I know JAVA 8 support Stream to group and aggregation but it's need to write hard code to do it, but i need define it in offline file.

**Comment by npgall** [comment]
I'm afraid this is not possible, as the SQL support in CQEngine does not extend to APIs outside of CQEngine itself such as to the Java Streams APIs.

This does seem like a good idea for a different project outside of CQEngine though, to implement SQL grouping and aggregation on top of the Streams API. Perhaps CQEngine could integrate with a project like that. Let me know if you decide to start a project like that! 😄

**Comment by CptGuo** [comment]
I  started a project for a year, in the project I need write a lot of script to archive  grouping and aggregation, like python script, it's terrible. 

My project it's a data collect system, it's collecting different data from Windows or linux like CPU  DISK MEMORY etc. and then set rule to check the CPU  DISK MEMORY data is OK or NOT, for example  cpu < 80%  use CQENGIN easy to done, but for DISK it's different.

A device has multiple hard drives and a lot of partitions for each hard disk. I need to check the total usage of the hard disk, berfor that i should GROUP the partitions for each hard disk and then check the hard disk usage status.
I got a lot of data like hard drive.
