### ISSUE TITLE
Performance is not looking correct 

### ISSUE THREAD

**Issue by muhdkhokhar** [npgall/cqengine#241]
I have this code

public class DemoApplication {

    public static void main(String[] args) throws InterruptedException {

        Properties pr = new Properties();
        pr.put("shared_cache",true);
        IndexedCollection<Car> cars = new ConcurrentIndexedCollection<Car>(DiskPersistence.onPrimaryKeyInFileWithProperties(Car.CAR_ID, new File("d:/cars.dat"), pr));
        cars.addIndex(NavigableIndex.onAttribute(Car.MODEL));

        log.info("Creating collection.");
        Set<Car> collectionOfCars = CarFactory.createCollectionOfCars(2_000_000);
        cars.addAll(collectionOfCars);
        log.info("Collection created");

        while (true) {
            log.info("-----------------------------------");
            log.info("Retrieving ...");
            List<Car> fusion = cars.retrieve(equal(Car.MODEL, "Fusion")).stream().collect(Collectors.toList());
            System.out.println(fusion.size());
            log.info("Retrieved");
        }

    }

}

I am adding around 2 Million Cars. But when I monitor the the memory itsconstantly very high though it should not be since I am using Disk persistence

![image](https://user-images.githubusercontent.com/7783228/62411239-f2609700-b5e7-11e9-8227-ec14eb6b8c47.png)

**Comment by npgall** [comment]
You are using a combination of DiskPersistence with an on-heap index there. NavigableIndex is heap-based.

If you switch to a DiskIndex instead, that should work.

**Comment by muhdkhokhar** [comment]
But if I switch to DiskInex the retrieval is very slow. It takes like 2-3 seconds for each query !

**Comment by npgall** [comment]
How many objects are you retrieving? I'd estimate several hundred thousand. Is that a realistic representation of what you will do in production?

You are also copying everything into a new collection, and calling size() on the new collection. This will bypass the CQEngine indexes for the computation of size. You should avoid copying results into other collections for each request, and just use the ResultSet directly. It can be iterated, and also the ResultSet.size() method can leverage indexes to compute the size.

**Comment by muhdkhokhar** [comment]
Yes in production it will be few thousands actually


Are you saying its taking time because of this 

> List<Car> fusion = cars.retrieve(equal(Car.MODEL, "Fusion")).stream().collect(Collectors.toList());

**Comment by muhdkhokhar** [comment]
You were right soon I changed 

 while (true) {
            log.info("-----------------------------------");
            log.info("Retrieving ...");
            int fusion = cars.retrieve(equal(Car.MODEL, "Fusion")).size();
            log.info("Size {}", fusion);

            log.info("Retrieved");
        }

Its quick now.

**Comment by muhdkhokhar** [comment]
Before closing this one last question

I am going to use disk based cache so multiple JVMS can use the same data runnong on same machine.

Is it thread-safe? 

What happens if JVM process # 01 is refreshing the cache while JVM process #02 was still retriving it will it throw any error?

**Comment by muhdkhokhar** [comment]
I tested it out myself. The change are visible to all JVMS

**Comment by npgall** [comment]
Behind the scenes, CQEngine uses SQLite for disk persistence. By default, it configures SQLite in WAL mode: https://www.sqlite.org/wal.html

Quote: _"All processes using a database must be on the same host computer; WAL does not work over a network filesystem."_

So take a look at the documentation link for WAL mode. If your application will be compliant with the requirements for WAL, then that should be ok actually.

If your application can't comply with the requirements, you can actually override the default config if you need to, and use the DELETE journaling mode instead:  https://www.sqlite.org/draft/lockingv3.html

The DELETE journaling mode is more compatible with sharing database files between multiple processes and machines, but has tradeoffs in terms of performance with WAL. Hopefully you can use WAL.

**Comment by muhdkhokhar** [comment]
I have windows server machine would “WAL” work ?

Sent from Mail for Windows 10

**Comment by npgall** [comment]
My guess is _probably_ but I don't know for sure. You'd need to check the documentation for the windows version of SQLite.

**Comment by muhdkhokhar** [comment]
Thanks. If you are using SQL Lite behind the scene how come its still so quick. Like taking less than 0 seconds to retrieve from 5 million entries?

Sent from Mail for Windows 10

**Comment by npgall** [comment]
Only the disk persistence and indexes use SQLite. But SQLite is actually
quite an efficient database.

If you have indexes on the fields you access, then it doesnt matter too
much how big the collection is. The time to retrieve a single item should
more or less be the same regardless of the collection size.

**Comment by muhdkhokhar** [comment]
I see. Awesome man. I’ll be using this now. Its speed is just amazing.

Sent from Mail for Windows 10

**Comment by muhdkhokhar** [comment]
Is there any chance at any point of time it may get corrupted? Also how can I delete the data from the cache may be older than certin time?
