### ISSUE TITLE
Issue using offheap with Spring

### ISSUE THREAD

**Issue by muhdkhokhar** [npgall/cqengine#243]
lets say I have car collection which is off-heap 

I initialized the colleciton.

I add 10 cars.

Now I have following method

```
ResultSet<Cars> get(final String query){

carCollection.retrieve(query)

}
```

It works first time. Second time it gets stuck. 

Even if I try to return stream and close the result set its nto working.

Whenever I even try to close the resultset it gets stuck.

But If I pass the collection to a generic method e.g

`Result<T> GenericUtil.get(collection . query)`

This works all the time.

**Comment by npgall** [comment]
Could you provide a test case to reproduce this?

**Comment by muhdkhokhar** [comment]
I think it was my issue. I am sorry Its nto an issue. 

I love your library sir.

QQ

I am planning to use CQEngine Disk cache as some data. Lets say later on I want remove any data older than 1 months. Does CQengine support purge etc?

**Comment by npgall** [comment]
To purge old items, I'd suggest to add a date field to your objects (such as seconds elapsed since epoch), and then to add an index on that. You can then just periodically delete items from the collection where the date < 1 month ago.
