### ISSUE TITLE
Offheap Result set closing Issue

### ISSUE THREAD

**Issue by muhdkhokhar** [npgall/cqengine#245]
Hi
I am writting a generic library in my code that returns the ResultSet based on the query.

The consumer does whatever it does.  They may read the stream or use the count. 

The issue is somtimes its putting a lock on the collectino and when getting the collection back it just hangs foreever.
After analying the code 

public Connection getConnection(Index<?> index, QueryOptions queryOptions) {
        // Acquire a read lock IFF the READ_REQUEST flag has been set, otherwise acquire a write lock by default...
        final Lock connectionLock = isFlagEnabled(queryOptions, READ_REQUEST)
                                        ? readWriteLock.readLock() : readWriteLock.writeLock();

        connectionLock.lock();
        Connection connection;
        try {
            connection = getConnectionInternal(index, queryOptions);
        }
        catch (RuntimeException e) {
            connectionLock.unlock();
            throw e;
        }
        return LockReleasingConnection.wrap(connection, connectionLock);
    }

This seems to be culprit.

I know you mentioned it that the result set should be closed. But I am not sure  how the client will close the result set.

Should I not return the resultset? If not then how can I write generic method like

<T> ResultSet<T> execute(Query q)

What are the options

**Comment by npgall** [comment]
There are not many options. It is the same situation as with JDBC, where it is up to the code which consumes a JDBC ResultSet, to close it when it has finished reading.

The ResultSet implements the AutoCloseable interface so it can easily be closed by a try-with-resources block.

**Comment by muhdkhokhar** [comment]
Are you suggesting that in that case I return the stream or the collection itself?

**Comment by npgall** [comment]
I'd suggest that  your API return the ResultSet, but you have to document in your API that the returned ResultSet must be closed.

Do you control the threads in the application? If so you could write a ThreadLocal, and before you return the ResultSet, store it in that ThreadLocal. That way, if the same thread happens to call your API again you could close the previous ResultSet then. But that is not ideal.

**Comment by muhdkhokhar** [comment]
Hmm interesting. What if I return teh stream would that close the resultset?

**Comment by muhdkhokhar** [comment]
What is the most efficient way to covert the restulset to the java collection

**Comment by muhdkhokhar** [comment]
Would this be good enough

```
public <T> List<T> executeQuery(final Query q)}

try(Stream s = myCollection.retrieve(q)){

return s.collect(Collectors.toList();
}

}
```

**Comment by npgall** [comment]
Yes, if you copy the results into a new collection, close the ResultSet, and return the new collection, it would work. You will have higher latency and memory utilization then of course. But there is no problem to do that, if it works for you.

**Comment by muhdkhokhar** [comment]
Hmmm thanks but how come its not issue with in heap
I tried and never get to close Results set
How much performance it will cost if i take above approach


Or

Can i use custom off heap persistence and ignore locking

Would that work

**Comment by muhdkhokhar** [comment]
I just eneded up creating a method that returns the collection. I am closing.
