### ISSUE TITLE
Disk persistence

### ISSUE THREAD

**Issue by muhdkhokhar** [npgall/cqengine#248]
Hi Nial

I am loving your library so far 

I have a question. Lets say I am dumping a lot data on disk and now the file is going over 100GB as the data grow obvsouly I have over TB of storage on the disk.

When I loading the data from the dispersistence based on the index which has maybe 100K records will it cause JVM issue considering the database is over 100GB now?

**Comment by npgall** [comment]
Thanks!

No, that should not be a problem. The size of the collection should not influence the amount of memory used if everything is stored on disk (assuming you are only using DiskIndex, and you avoid the other types of indexes which use the heap).

You just need to make sure that you have appropriate DiskIndexes of the fields you will query, to avoid filtering too much of the collection though.

**Comment by muhdkhokhar** [comment]
Thanks 
Basically this is my structure look like 

RunID (Unique and with disk index)
List anyData.

In that list I hold any collection and that goes to disk.

When I retrieve I use the runID to get the list of data.

Do you see any issue

**Comment by npgall** [comment]
That sounds perfectly fine. You should have no problem.

**Comment by muhdkhokhar** [comment]
Thanks a lot Nial. The only concern I have how do I setup the clean up on such structure. 

Lets say I want to delete anything older than 1 month.

**Comment by npgall** [comment]
Sorry, I forgot to post my answer to your other question. I've posted there now.
