### ISSUE TITLE
Question: Can I create an Attribute on Map type field

### ISSUE THREAD

**Issue by sourabh-ise** [npgall/cqengine#251]
taking the car example 
`public class Car {`
`    public final int carId;`
`   public final String name;`
`    public final List<String> features;`
`    public final Map<String,String> specifications;`
`}`

I need to create **Attribute** on specifications which is of type Map<String,String> so that I can query them on the basis of one or multiple map entries
eg: 
specifications for all cars need not have same keys 

- ("cc","800")
- ("sunroof","true")
- ("hybrid","false")

- so that I can query :
-get all cars that have sunrooof and are hybrid
or
-get all cards that have engine greater than 700 cc

**Comment by sourabh-ise** [comment]
Hi Niall

Figured it, hope this is the correct way.

```
public static final Attribute<Car, Entry<String, String>> SPECIFICATIONS= new MultiValueAttribute<Car, Entry<String, String>>("specifications") {
	@Override
	public Set<Entry<String, String>> getValues(Car car, QueryOptions queryOptions) {
		return car.specifications.entrySet();
	}
};
```
I must say great work. Thank you

**Comment by muhdkhokhar** [comment]
store the specification in collection and add indexes on those. that'd make more sense i think.
