### ISSUE TITLE
How to do efficient TOP N queries

### ISSUE THREAD

**Issue by nhaberl** [npgall/cqengine#257]
How we can handle TOP N queries for huge lists efficiently?
In my case I have lots of words indexed in a SuffixTrie with a weighting which gives the sortorder so to say.
I guess this is a common pattern for autocomplete scenarios so my question is how do I index the list correctly when retrieving TOP N records?

Thanks for this outstanding library!

**Comment by npgall** [comment]
If you want to retrieve the TOP N results, then you need to request that results should be [ordered by a specific attribute](https://github.com/npgall/cqengine#ordering-results). 

You then just need to read the first N objects from the ResultSet. The easiest way to do that is to create a [stream()](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/resultset/ResultSet.html#stream()) from the ResultSet, and then to call [limit()](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#limit-long-) on the stream.

Hope that helps!
Niall
