### ISSUE TITLE
Disk removal issue (TEST Case attached) ****URGENT*****

### ISSUE THREAD

**Issue by muhdkhokhar** [npgall/cqengine#261]
Hi 

Please have a look at example 

See the remove is not working 

I have attached all the classes please run the diskissue class.

```
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Created by muhdk on 20/11/2019.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Person {

    private String name;
    private BigDecimal age;
}
```

```

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Created by muhdk on 20/11/2019.
 */


@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DiskIssueClass {

    Long id;
    private List any;

}

```
```

import com.googlecode.cqengine.ConcurrentIndexedCollection;
import com.googlecode.cqengine.attribute.SimpleAttribute;
import com.googlecode.cqengine.persistence.disk.DiskPersistence;
import com.googlecode.cqengine.query.option.QueryOptions;

import java.io.File;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

/**
 * Created by muhdk on 20/11/2019.
 */
public class DiskBigDecimalIssue {

    public static void main(String[] args) {

        File dbFile = new File("D:/test.db");
        if (dbFile.exists())
            dbFile.delete();
        SimpleAttribute<DiskIssueClass, Long> simpleAttribute = new SimpleAttribute<DiskIssueClass, Long>() {
            @Override
            public Long getValue(DiskIssueClass object, QueryOptions queryOptions) {
                return object.getId();
            }
        };

        DiskPersistence<DiskIssueClass, Long> diskIssueClassIntegerDiskPersistence = DiskPersistence
                .onPrimaryKeyInFileWithProperties(simpleAttribute, dbFile, new Properties());

        ConcurrentIndexedCollection<DiskIssueClass> diskCollection = new ConcurrentIndexedCollection<>(diskIssueClassIntegerDiskPersistence);

        List<Person> personList = new ArrayList<>();

        personList.add(Person.builder().name("test").age(new BigDecimal("0")).build());
        personList.add(Person.builder().name("joh").age(new BigDecimal("0")).build());
        boolean add = diskCollection.add(DiskIssueClass.builder().id(1l).any(personList).build());

        System.out.println(add);

        DiskIssueClass diskIssueClass = diskCollection.stream().findAny().get();

        boolean remove = diskCollection.remove(diskIssueClass);

        System.out.println(remove);


    }
}
```

**Comment by npgall** [comment]
Your use of Lombok is masking what is going on, but essentially, you need to implement equals and hashCode.

FYI it is bad etiquette to supply a test case which isn't as [simple as it could be](http://sscce.org/). I only have limited time to work on CQEngine, intermittently. If a test case uses third party libraries unrelated to CQEngine (like Lombok here) or is otherwise overly complex, it means it can take more of my time to figure out what the problem could be. It will divert my time from other CQEngine development. Plus, the problem might actually be caused by those libraries, as is kind of the case here. Don't get me wrong, Lombok is great. But I maintain CQEngine not Lombok.

Anyway, I think here you just need to add another Lombok annotation to your class, [@EqualsAndHashCode](https://projectlombok.org/features/EqualsAndHashCode) to be precise.

**Comment by muhdkhokhar** [comment]
Hi 

Thanks for the reply.

I am extremely sorry but I didn't mean to annoy you. I am not just toying iwth your library instead now using it in alot of projects
Also writing generic storage engine based on CQEngine

I have been having this problem over a week and took me 3 days to come up with test case

As you suggested I have removed lombok completely 

attaching again

The issue is around **BigDecimal** if I set the value to 0 for both person then its not deleting it whie if i set to somethign else then it works 

so please have a look as I mentinoed took me more then 3 days to come up with test case.

```

import java.math.BigDecimal;

/**
 * Created by muhdk on 20/11/2019.
 */

public class Person {

    private String name;
    private BigDecimal age;

    public Person(String name, BigDecimal age) {
        this.name = name;
        this.age = age;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Person person = (Person) o;

        if (!name.equals(person.name)) return false;
        return age.equals(person.age);
    }

    @Override
    public int hashCode() {
        int result = name.hashCode();
        result = 31 * result + age.hashCode();
        return result;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getAge() {
        return age;
    }

    public void setAge(BigDecimal age) {
        this.age = age;
    }
}

```

```


import java.util.List;

/**
 * Created by muhdk on 20/11/2019.
 */

public class DiskIssueClass {

    Long id;
    private List any;

    public DiskIssueClass(Long id, List any) {
        this.id = id;
        this.any = any;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        DiskIssueClass that = (DiskIssueClass) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;
        return any != null ? any.equals(that.any) : that.any == null;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (any != null ? any.hashCode() : 0);
        return result;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List getAny() {
        return any;
    }

    public void setAny(List any) {
        this.any = any;
    }
}

```


```

import com.googlecode.cqengine.ConcurrentIndexedCollection;
import com.googlecode.cqengine.attribute.SimpleAttribute;
import com.googlecode.cqengine.persistence.disk.DiskPersistence;
import com.googlecode.cqengine.query.option.QueryOptions;

import java.io.File;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

/**
 * Created by muhdk on 20/11/2019.
 */
public class DiskBigDecimalIssue {

    public static void main(String[] args) {

        File dbFile = new File("D:/test.db");
        if (dbFile.exists())
            dbFile.delete();
        SimpleAttribute<DiskIssueClass, Long> simpleAttribute = new SimpleAttribute<DiskIssueClass, Long>() {
            @Override
            public Long getValue(DiskIssueClass object, QueryOptions queryOptions) {
                return object.getId();
            }
        };

        DiskPersistence<DiskIssueClass, Long> diskIssueClassIntegerDiskPersistence = DiskPersistence
                .onPrimaryKeyInFileWithProperties(simpleAttribute, dbFile, new Properties());

        ConcurrentIndexedCollection<DiskIssueClass> diskCollection = new ConcurrentIndexedCollection<>(diskIssueClassIntegerDiskPersistence);

        List<Person> personList = new ArrayList<>();


        personList.add(new Person("johnb",new BigDecimal("0")));
        personList.add(new Person("matthew",new BigDecimal("0")));
        boolean add = diskCollection.add(new DiskIssueClass(1L,personList));

        System.out.println(add);

        DiskIssueClass diskIssueClass = diskCollection.stream().findAny().get();

        boolean remove = diskCollection.remove(diskIssueClass);

        System.out.println(remove);


    }
}
```

**Comment by npgall** [comment]
It's an usual use case.

It looks like you are not storing Person objects in the IndexedCollection, you are storing Lists of Person objects instead?

In that case, CQEngine will rely on the Lists to implement equals and hashCode. The implementation of List.equals() will account for the order of the Person objects. Two lists containing the same Person objects, but in a different order will not be considered equal. I wonder if that could be a factor?

**Comment by muhdkhokhar** [comment]
I understand but how come it is only issue with Bigdecimal and only value with 0
while it works fine with other data types or even other values like 1 or 1.5

**Comment by npgall** [comment]
I am not sure actually. Does the problem occur if you just have an IndexedCollection of BigDecimal objects?

**Comment by muhdkhokhar** [comment]
If the object has Bigdecimal and you set value as 0

**Comment by muhdkhokhar** [comment]
I understand you are really busy but please do have a look at as its holding up my project and don't want to give up on this

**Comment by muhdkhokhar** [comment]
I think I found the root cause. 

When I retrieve back from the collection that is being de serialized by kryo 

the big decimal in both person are pointing to same memory address

**Comment by muhdkhokhar** [comment]
Its like a issue when the index collection has the list.

anyway I can delete using the value instead of the byte?

**Comment by npgall** [comment]
That sounds like a bug in Kryo. Could you test with a newer version of Kryo? (i.e. add a direct dependency in your project on a newer version of Kryo than CQEngine pulls in)

Also, it would be worth making a test case which tries to reproduce the problem with Kryo on its own, without CQEngine (so we know what we are dealing with).

If you need to override how CQEngine interacts with Kryo to serialize objects, in your application you can make a subclass of class [KryoSerializer](https://github.com/npgall/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/persistence/support/serialization/KryoSerializer.java). Then add a @[PersistenceConfig](https://github.com/npgall/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/persistence/support/serialization/PersistenceConfig.java) annotation in your POJO, like `@PersistenceConfig(serializer = <name of your serializer class>)`. This will instruct CQEngine to use your customized serializer instead of the built-in one.

As a workaround, if this is a bug in how Kryo is serializing BigDecimal, you could configure Kryo to use Java's built-in serialization for BigDecimal, instead of its own. Kryo provides some instructions for that [here](https://github.com/EsotericSoftware/kryo#javaserializer-and-externalizableserializer).

**Comment by muhdkhokhar** [comment]
I added 

<dependency>
    <groupId>com.esotericsoftware</groupId>
    <artifactId>kryo</artifactId>
    <version>5.0.0-RC4</version>
</dependency>
And now its working 
So you are right it was must be some issue with kryo

can you tell me if using that version would be fine 

I also suggest you put the some note as well for others.

**Comment by muhdkhokhar** [comment]
It must be fixed in RC2 release

https://github.com/EsotericSoftware/kryo/compare/kryo-parent-5.0.0-RC1...kryo-parent-5.0.0-RC2

Because it works with that

thanks a lot Nial.

Now I can still use this amazing library :)
