### ISSUE TITLE
Which index matched on?

### ISSUE THREAD

**Issue by muhdkhokhar** [npgall/cqengine#262]
If I have this code

```
Query<Car> query1 = or(endsWith(Car.NAME, "vic"), lessThan(Car.CAR_ID, 2));
  cars.retrieve(query1).forEach(System.out::println);
```

and I get the data. Is there way I can find out the record retrieved based on which condition. Was it either Car Name or Car ID ?

**Comment by npgall** [comment]
Unfortunately the engine itself does not support that (there is a number of reasons for this).

However, some partial workarounds:
1. _after_ you have retrieved a matching object, you could test which of the subqueries it matches by calling [Query.matches()](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/query/Query.html#matches(O,com.googlecode.cqengine.query.option.QueryOptions)). Most (sub-)queries don't use QueryOptions, so you can supply null for that argument.
2. You could retrieve results for the subqueries individual yourself, and basically implement the `or()` logic in your application. This would allow you to tell which subqueries are matched, but it won't allow CQEngine to optimize the lookup quite as much.

Hope that helps! Let me know if you need more info!
