### ISSUE TITLE
Calculate Memory consumption

### ISSUE THREAD

**Issue by nhaberl** [npgall/cqengine#265]
Hi, 
is there any way to determine the memory usage based on a given object and indexes?

Would be very helpful

**Comment by npgall** [comment]
This is supported for off-heap and disk persistence, but not for on-heap persistence.

You can call [DiskPersistence/OffHeapPersistence.getBytesUsed()](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/persistence/disk/DiskPersistence.html#getBytesUsed())

You could also read about the `compact()` method in those classes, as a way to reduce memory fragmentation and usage.
Hope that helps!
