### ISSUE TITLE
SQLite dependency

### ISSUE THREAD

**Issue by EPluribusUnum** [npgall/cqengine#266]
Hi!

I started to use CQEngine for in-memory caching: I use ConcurrentIndexedCollection + OnHeapPersistence.

My compiled über-jar now contains SQLite because of CQE. SQLite is essential party of the engine, or it can be left out **safely** in this case? Basic tests showed no problems removeign SQLite from the über-jar. If possible, it woud be great to have a small footprint version of CQE without SQLite.

I use this Maven version : https://mvnrepository.com/artifact/com.googlecode.cqengine/cqengine/3.5.0

Thank you.

**Comment by npgall** [comment]
Hi,

You can safely omit the SQLite dependency if you are not using it. That dependency is intentionally kept at "arms length" in the code (i.e. it is only used where needed), so that it can be omitted where it is not needed.

Let me know if you need more info.

Best regards,
Niall
