### ISSUE TITLE
Strange behaviour with index based on Boolean field

### ISSUE THREAD

**Issue by Verdoso** [npgall/cqengine#267]
Hi there,
I have a SimpleAttribute<Element,Boolean> index added as HashIndex.onAttribute on a ConcurrentIndexedCollection and I'm experiencing a strange issue: When I query the collection based on that index, if I use:

```equal(INDEX_ON_BOOLEAN, Boolean.FALSE);```

the results return all the elements on the collection, independently of the boolean field. On the other hand, if I query using:

```not(equal(INDEX_ON_BOOLEAN Boolean.TRUE));```

I get the desired results and only the elements with that flag to Boolean.FALSE are returned. I have verified that there are no other criteria involved in the query and reduced the changes to just that...

What could be the problem? Am I doing something wrong?
Cheers!

PS:
CQengine: 3.5.0
Java 1.8

**Comment by npgall** [comment]
Hi, sorry for the delay replying.

I was not able to reproduce this in a quick test I ran locally. Any chance you could share something like a unit test which demonstrates the problem? (Please include the source for your Element class and your attribute as well)

**Comment by Verdoso** [comment]
I'll see if I can reduce the problem to something easy to check.

**Comment by Verdoso** [comment]
After being unable to reproduce... I checked again and now it works... so it must be something I had in my code. My bad :(.
Thinking about it, I probably introduces some elements in the collection where the Boolean was a null, so not equal to true was not the same as equal to false... I'm initialising the default value, false, at declaration, so not sure how that happened.

Sorry about that

**Comment by npgall** [comment]
No problem. Glad you got it sorted anyway!
