### ISSUE TITLE
Grouping and Aggregation support

### ISSUE THREAD

**Issue by zhanglinqiang** [npgall/cqengine#285]
HI 
**Can CQENGINE support  Grouping and Aggregation ?**

Next is my problem.

I started a project for a year, in the project I need write a lot of script to archive grouping and aggregation, like python script, it's terrible.

My project it's a data collect system, it's collecting different data from Windows or linux like CPU DISK MEMORY etc. and then set rule to check the CPU DISK MEMORY data is OK or NOT, for example cpu < 80% use CQENGIN easy to done, but for DISK it's different.

A device has multiple hard drives and a lot of partitions for each hard disk. I need to check the total usage of the hard disk, berfor that i should GROUP the partitions for each hard disk and then check the hard disk usage status.
I got a lot of data like hard drive.

**Comment by npgall** [comment]
There is a section in the main Readme about that: https://github.com/npgall/cqengine#grouping-and-aggregation-group-by-sum

As mentioned, Streams can be used for that. There are no plans to duplicate that functionality inside CQEngine itself.

However that said, there are some metadata APIs in CQEngine that can provide some statistics and frequency distributions etc; those APIs can sometimes be useful when aggregating data too: https://github.com/npgall/cqengine#accessing-index-metadata-and-statistics-from-metadataengine
