### ISSUE TITLE
Offheap cache visibility

### ISSUE THREAD

**Issue by muhdkhokhar** [npgall/cqengine#306]
Hi
If I use offheap cache will that be also visible to other JVM processess on same machine?

**Comment by npgall** [comment]
No it will not. The offheap cache is stored in the memory owned by the local JVM process only.

You could probably use disk persistence instead though, and locate the persistence file on an in-memory file system. However, inter-process thread safety could be compromised. I would recommend to do that only for static collections which are not modified at runtime.
