### ISSUE TITLE
Does it support SQL statistics queries 

### ISSUE THREAD

**Issue by wwwzzz5199** [npgall/cqengine#309]
Does it support SQL statistics queries, such as “select count(id),sum(price),name from table group by name"

**Comment by npgall** [comment]
No, that is not supported.

The SQL parser aims to convert SQL queries into CQEngine
native/programmatic queries under the hood. So it does not support any
functionality that is not available via native queries. CQEngine is aimed
more at OLTP (retrieving results that match criteria) than OLAP (analytics).

There are some APIs for obtaining statistics about the data that is stored
though.
https://github.com/npgall/cqengine#accessing-index-metadata-and-statistics-from-metadataengine

But those APIs do not operate on queries.

Best regards,
Niall

**Comment by npgall** [comment]
I will close this. Feel reopen if you need more info, thanks
