### ISSUE TITLE
What is use of sqlite-jdbc in cqengine

### ISSUE THREAD

**Issue by Nikhilkarande33** [npgall/cqengine#317]
Hi Team, 

we found new vulnerability introduced in sqlite-jdbc library, so we need to get rid of it.

during analysis, we found sqlite-jdbc coming via cqengine. 

<img width="523" alt="image" src="https://github.com/npgall/cqengine/assets/56636720/16180215-90f7-416d-ad0b-49a90bbf35ab">

we downloaded cqengine source code, there is no use of sqlite-jdbc in cqengine.

Anyone can explain or move sqlite-jdbc to non-vulnerable version

@npgall

**Comment by npgall** [comment]
SQLite is [used in the off heap and disk indexes](https://github.com/npgall/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/index/sqlite/SQLiteIndex.java).

You can add a dependency on a newer version of sqlite-jdbc in your application (and CQEngine will use it), or exclude the dependency yourself.

There should not be any programmatic dependency on SQLite via CQEngine if you don't use those indexes in your application. It should work fine without it.

**Comment by Nikhilkarande33** [comment]
Thanks @npgall for your timely support.
