### ISSUE TITLE
Index updated even though objectStore is not modified during IndexedCollection add

### ISSUE THREAD

**Issue by ronyjhn** [npgall/cqengine#318]
Why indexes are updated even though object store is not modified as object already present in collection?

**Comment by npgall** [comment]
Is this a problem?

Index updates should be idempotent if an already-stored object is added to the collection again.

Implementing an additional check to see if every object being added to the collection is already stored would incur more overhead. There are [TOCTOU race conditions](https://en.m.wikipedia.org/wiki/Time-of-check_to_time-of-use) that would need to be considered as well.

If an application needs that functionality it can use collection.contains() before adding an object, if it can work around the TOCTOU issue.

**Comment by ronyjhn** [comment]
Thank you so much for the clarification. In my scenario, all collection updates are from single thread, so hope TOCTOU  wont affect.
