### ISSUE TITLE
Primitive Specialisations

### ISSUE THREAD

**Issue by sirinath** [npgall/cqengine#46]
Unless you are already doing this some form of primitive specialisation may increase speed.

**Comment by npgall** [comment]
Hi Suminda, it will not be possible to implement primitive specialisations in the engine itself as it needs to remain generic and support non-primitive types. I'll close this as there's not much that can be done. 

However it would be possible to write an index which uses primitive specialisations internally. So if you would like to do something like this yourself, remember this project is open to pull requests! 

Best regards,
Niall
