### ISSUE TITLE
Find two java files

### ISSUE THREAD

**Issue by lveyna** [npgall/cqengine#50]
Hi, recently I download the source code, but, I did'nt found the files:

import com.googlecode.cqengine.query.parser.sql.grammar.SQLGrammarLexer;
import com.googlecode.cqengine.query.parser.sql.grammar.SQLGrammarParser;

In the java class:
com.googlecode.cqengine.query.parser.sql.SQLParser

Can you help me? 

Thanks

**Comment by npgall** [comment]
If you run mvn compile, or mvn generate-sources, it should work.
