### ISSUE TITLE
Making ResultSet implement Closeable?

### ISSUE THREAD

**Issue by yrashk** [npgall/cqengine#52]
Have you considering implementing Closable interface on ResultSet in order to get an advantage of try-with-resources https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html ? That would certainly improve the quality of my code :)

**Comment by npgall** [comment]
Hi yrashk, this would be a good improvement. There will be a major new version of CQEngine, probably 3.x, in the next few months, which finally targets Java 8 and I will try to include this improvement in that release. I will keep this issue open until it's implemented. Many thanks!

**Comment by npgall** [comment]
BTW are you using Java 8, or Java 7?

**Comment by yrashk** [comment]
I'm using Java 8

On Tuesday, 16 February 2016, Niall Gallagher <notifications@github.com>
wrote:

> BTW are you using Java 8, or Java 7?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npgall/cqengine/issues/52#issuecomment-184796550>.
>


-- 
Y.

**Comment by npgall** [comment]
Ok great :)

**Comment by yrashk** [comment]
Also, very excited to follow the 3.x development, I am using cqengine heavily right now in https://github.com/eventreducer/eventreducer used in real projects. Is there a roadmap?

**Comment by npgall** [comment]
Cool! :)

Well CQEngine 3.x probably won't be much different from CQEngine 2.x at all. It's just that if I break compatibility with Java 6, it probably deserves a major bump in the version number.

Breaking compatibility with Java 6 would finally allow me to add support to create CQEngine attributes directly from Java 8 Method References, and to allow tighter integration with lambda expressions.

So no radical changes are planned, just a few improvements basically :) 3.x would almost definitely be backward compatible with applications already using CQEngine 2.x.

**Comment by npgall** [comment]
I implemented this in the 2.x series after all, and I've just released it in CQEngine 2.1.3. Thanks for the suggestion!
