### ISSUE TITLE
Upgrade dependencies to Kryo 3.0.3 and kryo-serializers 0.37

### ISSUE THREAD

**Issue by yrashk** [npgall/cqengine#56]
While trying to deploy an OSGi application, I ran into a versioning issue. In your pom.xml:

```xml
   <dependency>
            <groupId>com.esotericsoftware</groupId>
            <artifactId>kryo</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>de.javakaffee</groupId>
            <artifactId>kryo-serializers</artifactId>
            <version>0.28</version>
            <exclusions>
                <exclusion>
                    <groupId>com.esotericsoftware.kryo</groupId>
                    <artifactId>kryo</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

However, if we look here http://search.maven.org/#artifactdetails%7Cde.javakaffee%7Ckryo-serializers%7C0.28%7Cbundle

We will see that in its OSGi bundle manifest, there's a strict requirement on kryo (< 3.0):

```
com.esotericsoftware.kryo*;version="[2.24.0,3.0)",
```

Any chance we can go to kryo-serializers/0.37? Their requirement is a better fit:

```
com.esotericsoftware.kryo*;version="[3.0.3,4.0)",
```

It will, however, require an upgrade of kryo to 3.0.3:

```xml
  <dependency>
            <groupId>com.esotericsoftware</groupId>
            <artifactId>kryo</artifactId>
            <version>3.0.3</version>
        </dependency>
```

But since you already require 3.0.0 I suspect 3.0.3 is just a minor release. From their changelog, it looks mostly like bug fixes: https://github.com/EsotericSoftware/kryo/blob/master/CHANGES.md

Thanks!

**Comment by npgall** [comment]
Hi Yurii,

Yes that will be no problem.
I will upgrade to Kryo 3.0.3 and kryo-serializers 0.37 for the next release.

BTW it probably looks like there's not much development at the moment, but actually there is. I'm in the middle of a huge chunk of work for a CQEngine 2.2 release, which I'm hoping to commit and release in the next 2-3 weeks.

I'll keep this issue open until its done and released.
Best regards,
Niall
