### ISSUE TITLE
How to query map-based 'records' ?

### ISSUE THREAD

**Issue by albert-kam** [npgall/cqengine#63]
Hello, i wonder if defining attributes for a map-based record works ? 
I'm trying to use `new ReflectiveAttribute(Map.class, String.class, "name")`, but failed with errMsg saying that `name` doesnt exist in map.

Here's my code: 

    public class ObjectQueryLab {
        @SuppressWarnings({ "unchecked", "rawtypes" })
        public static void main(String[] args) {
            List<Map<String, Object>> records = Lists.newArrayList(
                    createPerson("robert", 35, DateTime.now()),
                    createPerson("peter", 32, DateTime.now()));

            IndexedCollection<Map<String, Object>> collection = 
                    new ConcurrentIndexedCollection<Map<String, Object>>();
            collection.addAll(records);

            Map<String, ReflectiveAttribute> attributes = 
                    new ImmutableMap.Builder<String, ReflectiveAttribute>()
                .put("name", new ReflectiveAttribute(Map.class, String.class, "name"))
                .put("age", new ReflectiveAttribute(Map.class, Integer.class, "age"))
                .put("createdWhen", new ReflectiveAttribute(Map.class, DateTime.class, "createdWhen"))
                .build();

            Query<Map<String, Object>> query1 = or(endsWith(attributes.get("name"), "ert"),
                    lessThan(attributes.get("age"), 40));

            for (Map<String, Object> record: collection.retrieve(query1)) {
                System.out.println(JsonUtil.prettyString(record));
            }
        }

        private static Map<String, Object> createPerson(String name, int age,
                DateTime createdWhen) {
            return ImmutableMap.<String, Object> builder()
                    .put("id", new IdKey())
                    .put("name", name)
                    .put("age", age)
                    .put("createdWhen", createdWhen).build();
        }
    }

The exception that i had is:

    Exception in thread "main" java.lang.IllegalStateException: Invalid attribute definition: No such field 'name' in object 'java.util.Map'
        at com.googlecode.cqengine.attribute.ReflectiveAttribute.<init>(ReflectiveAttribute.java:51)
        at app.lab.ObjectQueryLab.main(ObjectQueryLab.java:33)

**Comment by kimptoc** [comment]
Hi - I don't think that works with Maps.

You'll need to do something like on this link - https://github.com/npgall/cqengine/issues/62

Although looking at making it work better

**Comment by albert-kam** [comment]
Hi, thanks for the quick reply.
I tried making a custom SimpleAttribute subtype, and seems to be working pretty well, even for filtering based on nested map field values.

    public class ObjectQueryLab {
        @SuppressWarnings({ "unchecked" })
        public static void main(String[] args) {
            List<Map<String, Object>> records = Lists.newArrayList(
                    createPerson("albert", "handsome", 35, DateTimeManager.now()),
                    createPerson("novita", "pretty", 32, DateTimeManager.now()));

            queryWithCpengine(records);
        }

        @SuppressWarnings({ "unchecked", "rawtypes" })
        private static void queryWithCpengine(List<Map<String, Object>> records) {
            IndexedCollection<Map<String, Object>> collection = new ConcurrentIndexedCollection<Map<String, Object>>();
            collection.addAll(records);

            Map<String, SimpleAttribute> attributes = new ImmutableMap.Builder<String, SimpleAttribute>()
                    .put("name.first", new MapAttribute("name.first"))
                    .put("name.last", new MapAttribute("name.last"))
                    .put("age", new MapAttribute("age"))
                    .put("createdWhen", new MapAttribute("createdWhen"))
                    .build();

            Query<Map<String, Object>> query1 = and(
                    endsWith(attributes.get("name.first"), "ert"),
                    lessThan(attributes.get("age"), 40)
            );

            for (Map<String, Object> record: collection.retrieve(query1)) {
                System.out.println(JsonUtil.prettyString(record));
            }
        }

        private static Map<String, Object> createPerson(String firstName, String lastName, int age,
                DateTime createdWhen) {
            return ImmutableMap.<String, Object>builder()
                    .put("id", new IdKey())
                    .put("name", ImmutableMap.<String, Object>builder()
                            .put("first", firstName)
                            .put("last", lastName)
                            .build())
                    .put("age", age)
                    .put("createdWhen", createdWhen).build();
        }

        private static class MapAttribute extends SimpleAttribute<Map<String, Object>, Object> {
            private String attrPath;

            public MapAttribute(String attrPath) {
                this.attrPath = attrPath;
            }

            @Override
            public Object getValue(Map<String, Object> object, QueryOptions queryOptions) {
                // org.azeckoski.reflectutils.ReflectUtils
                return ReflectUtil.getFieldValue(object, this.attrPath);
            }
        }
    }

**Comment by albert-kam** [comment]
Just wanna share the latest progress. I am a bit lazy to specify manually for each map record types, so i kind of make it simpler to auto-generate the mapAttribute lazily:

    public class ObjectQueryLab {
        @SuppressWarnings({ "unchecked" })
        public static void main(String[] args) {
            List<Map<String, Object>> records = Lists.newArrayList(
                    createPerson("albert", "handsome", 35, "read", DateTimeManager.now()),
                    createPerson("novita", "pretty", 32, "cook", DateTimeManager.now()));

            queryWithCpengine(records);
        }

        @SuppressWarnings({ "unchecked" })
        private static void queryWithCpengine(List<Map<String, Object>> records) {
            IndexedCollection<Map<String, Object>> collection = new ConcurrentIndexedCollection<Map<String, Object>>();
            collection.addAll(records);

            // no need to supply each field attributes anymore
            MapAttributeSupplier attributes = new MapAttributeSupplier();
            Query<Map<String, Object>> query = and(
                    in(attributes.of("hobbies"), "read", "code"),
                    endsWith(attributes.of("name.first"), "ert"),
                    lessThan(attributes.of("age"), 40)
            );

            for (Map<String, Object> record: collection.retrieve(query)) {
                System.out.println(JsonUtil.prettyString(record));
            }
        }

        private static Map<String, Object> createPerson(String firstName, String lastName, int age,
                String hobby, DateTime createdWhen) {
            return ImmutableMap.<String, Object>builder()
                    .put("id", new IdKey())
                    .put("name", ImmutableMap.<String, Object>builder()
                            .put("first", firstName)
                            .put("last", lastName)
                            .build())
                    .put("age", age)
                    .put("hobbies", hobby)
                    .put("createdWhen", createdWhen).build();
        }

        private static class MapAttributeSupplier {
            private Map<String, MapAttribute> cache = Maps.newHashMap();

            @SuppressWarnings("rawtypes")
            public SimpleAttribute of(String attrPath) {
                MapAttribute attr = null;
                if (this.cache.containsKey(attrPath)) {
                    attr = this.cache.get(attrPath);
                } else {
                    attr = new MapAttribute(attrPath);
                    this.cache.put(attrPath, attr);
                }
                return attr;
            }
        }
        private static class MapAttribute extends SimpleAttribute<Map<String, Object>, Object> {
            private String attrPath;

            public MapAttribute(String attrPath) {
                this.attrPath = attrPath;
            }

            @Override
            public Object getValue(Map<String, Object> object, QueryOptions queryOptions) {
                // org.azeckoski.reflectutils.ReflectUtils
                return ReflectUtil.getFieldValue(object, this.attrPath);
            }
        }
    }

**Comment by kimptoc** [comment]
Nice - I don't see any addIndex calls - are they done elsewhere?  My understanding is that you will get a brute force search unless you add an index... unless it adds them automatically based on queries...

**Comment by albert-kam** [comment]
Ow shoot, you're right, i totally forgot about it !

I guess if i want to use indexing, i'd have to avoid using the attribute-auto-generations on the indexed fields.

And in my case, the collection would be so shamefully small that i think i can skip indexing.

I just hope map based attribute could be added to the core library in the future release, because im not sure this workaround is the right way.

**Comment by npgall** [comment]
Your current approach looks fine Albert. Adding indexes is optional.

It's coincidental that you asked about this today, because we are literally integrating map attributes into the core library right now! It's currently in dev branch: issue-62-map-attributes, but we will merge it into mainline soon.

**Comment by albert-kam** [comment]
Thanks for helping out !

**Comment by npgall** [comment]
Closing this. Support for map-based records has been added, and will be included in the next release.
