### ISSUE TITLE
Any plans to switch to Java 1.7 as the minimum requirement to build cqengine?

### ISSUE THREAD

**Issue by kimptoc** [npgall/cqengine#64]
Java 1.6 is a bit long in the tooth.

Admittedly, I don't have specific requirements for using a more recent version.

Would start with updating the maven pom to specify source/target 1.7 and then just let 1.7 features be used as appropriate.

**Comment by kimptoc** [comment]
Just tried comparing the timings via my tests project - https://github.com/kimptoc/cqengine-test - and there does seem to be a small gain when using a jar built for 1.7.

**Comment by npgall** [comment]
CQEngine is compiled with Java 8, but targeting Java 6. I plan to skip Java 7 entirely. The next major release of CQEngine will target Java 8. This is discussed in issue #48 . The version of Java that a library was compiled with rarely impacts runtime performance. It's the runtime version which implements hotspot. I'll close this as it's tracked in issue #48.
