### ISSUE TITLE
TransactionalIndexedCollection and iterating over it

### ISSUE THREAD

**Issue by kimptoc** [npgall/cqengine#66]
Hi,

When you iterate over a TransactionalIndexedCollection does it honour READ_COMMITTED transaction isolation ?

Or should we use retrieve to get the whole collection to get a consistent view?

Thanks,
Chris

**Comment by npgall** [comment]
No, iterating the TransactionalIndexedCollection does not provide READ_COMMITTED isolation. 

You need to to call TransactionalIndexedCollection.retrieve(all(..)) instead.

BTW you can also ask questions in the [discussion forum](http://groups.google.com/forum/#!forum/cqengine-discuss) :)

**Comment by kimptoc** [comment]
Thanks - and keep forgetting about the forum - doh :(
