### ISSUE TITLE
Intermittent NullPointerException when retrieving from TransactionalIndexedCollection which is being updated

### ISSUE THREAD

**Issue by kimptoc** [npgall/cqengine#69]
We have some code that is doing a lot of updates to a TransactionIndexedCollection in one thread and then another thread that is reading the same object.

We are getting intermittent NPEs when doing the retrieve, it seems to be getting confused about the version.

Here is the stack trace - see attached image showing the debugger when this happens.

```
java.lang.NullPointerException
	at com.googlecode.cqengine.TransactionalIndexedCollection.retrieve(TransactionalIndexedCollection.java:367)

```

![retrieve-npe](https://cloud.githubusercontent.com/assets/38746/15885290/20c8f22a-2d4e-11e6-8dd5-c5ecee5596ac.png)

I am trying to but failing (so far) to produce a standalone test of this issue - but thought I'd raise it, in case something comes to mind.

**Comment by kimptoc** [comment]
Ok - I have a more involved test but it gives the problem, if you run TestIMDB from here:  https://github.com/kimptoc/cqengine-test/tree/master/src/main/java/threaded/imdb

I am sure its a bug in my (mis)use of IndexedCollection.

**Comment by kimptoc** [comment]
The issue seems to be possible overlap between retrieve and waitForReadersOfPreviousVersionsToFinish.

waitForReadersOfPreviousVersionsToFinish
```
            if (previousVersion.readersCount.get() != 0) { // W1
                previousVersion.writeLock.acquireUninterruptibly();
            }

            // At this point readers of this previous version have finished.
            // Remove this version from memory...
            previousVersionsIterator.remove();  // W2
```

retrieve
```
        final long thisVersionNumber = currentVersion; // R1
        final Version thisVersion = versions.get(thisVersionNumber); // R2
        // Increment the readers count to record that this thread is reading this version...
        thisVersion.readersCount.incrementAndGet(); // R3
```

I think things could happen in this order:
R1 - get current version number
W1 - reader count is checked, no readers, so no need to wait
W2 - remove the version
R2 - tries to get the version, but fails as its gone
R3 - gets a NPE.

Thoughts on how to fix it:

1. make the reader loop until it can successfully get the current version and increment its readercount.
2. ???

**Comment by npgall** [comment]
Hi Chris,

Nice find, yes I think you are correct.

Thanks especially for providing all of these details! With these root cause details it should be easy to fix.

I will fix this in the next release, ETA in the next few days.

Niall

**Comment by kimptoc** [comment]
Great - the latest code does not seem to compile for me, something a remove method on FilterObjectStore.  Is there a CI build for this project - I could setup a TravisCI build for it?

**Comment by kimptoc** [comment]
I added a remove implementation, like so 

```
        return new CloseableIterator<O>() {
            @Override
            public void remove() {
                filteringIterator.remove();
            }
```

This patch has fixed both my issue with the NPE and the intermittent empty result issue mentioned on the discussion forum :)

**Comment by npgall** [comment]
This missing method is fixed. (It was a Java 8 vs Java 6 problem)

Yes I think the patch above should fix the NPE, and that's great to know it fixed the empty result issue too!

This detailed bug report was very helpful Chris. Much appreciated, thanks!
