### ISSUE TITLE
Bundle for OSGi environments

### ISSUE THREAD

**Issue by efernandezleon** [npgall/cqengine#71]
Hi, in our company we use some OSGi frameworks like Eclipse Equinox or Virgo, so we need to have every library with OSGi headers in the MANIFEST.MF. I've created a bundle of CQEngine for OSGi with external libraries in the bundle-classpath in this repo https://github.com/intelliment/cqengine-osgi .

Let reference in your doc if you consideer appropriate.

Regards,
Eduardo F.

**Comment by npgall** [comment]
Hi Eduardo,

Would it be feasible to integrate this into CQEngine library itself? I got a request like this for one of my other projects recently, and merged OSGi support in via a [pull request](https://github.com/npgall/concurrent-trees/pull/16).

Would you like to submit a pull request for this? I do have the same concerns regarding OSGi as I had in the PR I linked above for my other project. But as long as you can say the OSGi support will not hinder non-OSGi users of CQEngine then I'd be happy to merge a PR.

Thanks,
Niall

**Comment by efernandezleon** [comment]
Hi Niall,

My approach is a little different. In my case, CQEngine has dependencies that they are not _OSGIfied_ , so for us, is better to include every third-party dependency inside of the JAR using OSGi techniques. This approach is OK for everyone who wants an all-in-one OSGi bundle with CQEngine without worrying about others libraries and versions.

The approach in the other pull request consists in to OSGify only the CQEngine library, delegating to the user the wiring for external libraries.

I think I have a solution that covers both approaches: creating by default an OSGi bundle that will be compatible with non-OSGi users, and creating the all-in-one bundle with a Maven profile.

Let me test it and will submit a pull request.

Regards,
Eduardo F.

**Comment by npgall** [comment]
Cool, sounds good. Btw in case it helps, there is already a build of
CQEngine built using the maven-shade-plugin, which bundles all of the
dependencies into a single jar. Although it is not configured for OSGi.
However the SQLite library is an exception to the rule as it does not like
to be relocated.

**Comment by efernandezleon** [comment]
I've just to create the PR https://github.com/npgall/cqengine/pull/72 . Both approaches commented before are supported :D 

Regards,
Eduardo F.

**Comment by npgall** [comment]
Thanks Eduardo, that’s great! I will look at merging this next week. Many thanks!
