### ISSUE TITLE
Need of matcher.find() method of java regex to be accessible via CQ Engine

### ISSUE THREAD

**Issue by abhilashkkale** [npgall/cqengine#73]
Hi Niall,
I have a use case where I want to search for sensitive information in a string like email id in a text from a collection of string.
For that I am in the need of matcher.find() method of java regex but it seems to be not supported in CQEngine. CQEngine has matches method for regex pattern matching.
So can you please provide a solution for this or add the find method of java regex into CQEngine ?

Thanks.

Regards,
Abhilash K.

**Comment by npgall** [comment]
Can you add a new StringRegexFinds query yourself, and submit it, with unit tests, as a Pull Request?

It seems it should be quite similar to [this one](https://github.com/npgall/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/query/simple/StringMatchesRegex.java), so not that hard to implement. 

This project is open to improvements you can make via pull request :)

Thanks,
Niall

**Comment by abhilashkkale** [comment]
Thanks Niall,
 I will do it.

Regards,
Abhilash K.

**Comment by npgall** [comment]
Thanks Abhilash. I'll close this issue and await a pull request. Let me know if you need any help! 
Best regards, Niall
