### ISSUE TITLE
byte[] equality?

### ISSUE THREAD

**Issue by yrashk** [npgall/cqengine#75]
I just ran into an issue of having an EQ index that returned byte[] — and when I queried against it (obvious in the hindsight) I never got the correct results because of how java byte array equality works.

Any chance this can somehow be circumvented in cqengine. Any suggestion on the best way to deal with this? I currently convert this byte[] to a Comparable (for the sake of the experiment, a base64-encoded String) and that works, but I find this a bit ugly.

**Comment by npgall** [comment]
Hi Yuri,

The best way is to wrap the byte[] in a POJO object which implements equals() and hashCode() correctly. Something like class ByteArray.
