### ISSUE TITLE
Gratipay - is there a CQEngine account or plans to set one up?

### ISSUE THREAD

**Issue by kimptoc** [npgall/cqengine#76]
https://gratipay.com/

**Comment by npgall** [comment]
Thanks for the thought Chris :) I don't have such account at the moment.

My company [Synchronoss](http://synchronoss.com/) do sponsor CQEngine development though, to add features we need.

So I guess I do get paid to work on CQEngine indirectly already, and Synchronoss sfaff make contributions as well which is nice.

I/we should publicise or write a blog about this! But we have CQEngine in production in many of the largest Tier 1 Mobile networks around the world actually, and we've added several new index types to CQEngine to support what we need.

I think if I accepted payment for CQEngine outside of my current employer though, it may create a conflict of interest against my employment contract. So this is something I might revisit in a few years!

In the meantime please enjoy CQEngine free of charge!

**Comment by kimptoc** [comment]
Many Thanks then Niall :)

Was thinking of the equivalent of buying you a coffee, but I appreciate your situation.

Cheers,
Chris
