### ISSUE TITLE
[Question] Is there a way to filter the results of a Nested Object Query ?

### ISSUE THREAD

**Issue by jarey** [npgall/cqengine#77]
Hi,

First of all, thanks for the great effort making CQEngine.

We are considering the use of the library for one of our projects and one doubt we are having is that if its possible to get the results of a Nested Object Query, filtered against the conditions applied to the query itself. (I know the actual questions seems a non-sense)

Being more concise, and refferring an example:
https://github.com/npgall/cqengine/blob/master/code/src/test/java/com/googlecode/cqengine/examples/nestedobjects/NestedObjectsExample.java#L78

Is there a way i could get the User filtered only with the products matching "Snickers Bar" without indexing the collections separately and making a join between them, instead of the user with all of the values contained on its collection?

Thanks in advance!

**Comment by npgall** [comment]
Hi Jarey,

I'm not sure if I understand fully. Can you provide an example of what you are trying to do?

You have a few options for this kind of thing:
(1) You can query nested objects as in the [example](https://github.com/npgall/cqengine/blob/master/code/src/test/java/com/googlecode/cqengine/examples/nestedobjects/NestedObjectsExample.java#L78) you linked, or
(2) you can make [joins](https://github.com/npgall/cqengine/blob/master/documentation/Joins.md) between two separate IndexedCollections, or
(3) you can write virtual attributes for your main object, which retrieve data from some other collection or data source

**Comment by jarey** [comment]
Hello npgall,

Thanks for your kind reply.

What i mean is if theres is a mechanism in the library that can return the results of the query, applied to the element i'm indexing and its nested objects. 

Referring to the NestedObject example, i would like to obtain the result of the Users that have bought a product "Snickers Bar", with the user collection returned by the search only cointaining the subslists of orders cointaining the "Snickers Bar" and the sublist of products only containing the actual "Snickers Bar" element. So that would be not only the Users matching the query but that lists and sublists filtered by the actuals conditions expressed, that are applied to the subslists elements (I know it probably has no sense in terms of the library)

The join would solve that requierement but in my scenario i would prefer avoiding iterating over the user lists only for indexing all the orders and products sublists in another 2 IndexedCollections (in order to be able to join them). Another option would be to pre-process the data and make it flat in order to make the sublists disappear and search only over 1 collection, but it would be time-consuming.

For us the data structure we are managing follows the same structure as the example, so i'm asking by curiosity since dont know cqengine very well. If the library has something to achive it, would be awesome for us.

Don't know what the Virtual Attribute approach is, so i would take a look.

Again, thank you very much for your time and sorry about the long explanation.

**Comment by npgall** [comment]
Hi jarey,

I see. In the case of nested objects, CQEngine _itself_ doesn't actually store a connection between the outer objects and the nested objects.

For example in the NestedObjectsExample we discussed above, the PRODUCT_NAMES_ORDERED attribute just returns to CQEngine a list of String product names which are to be associated with each User object.

If an application were then to add an index on the PRODUCT_NAMES_ORDERED attribute, the index would simply be structured like a Map<String, Set<User>>. It would allow CQEngine to quickly retrieve a set of User objects who had ordered a product with a particular name, but the relationship from User -> Order -> Product -> Product name would not be known.

So I think your best bet might be to just have two IndexedCollections: an IndexedCollection<User> which (as discussed above) allows you to retrieve User objects who ordered a particular product by specifying the product name, and an IndexedCollection<Product> which allows you to retrieve the full Product object given a product name.

As with many things this kind of problem can be solved in many ways! I hope that helps, somehow!

**Comment by jarey** [comment]
Hi npgall,

Of course it helps, thank you very much for your time and kind answers. Very appreciated.

Kind regards.
