### ISSUE TITLE
IndexedCollection#removeIndex and/or IndexedCollection#hasIndex

### ISSUE THREAD

**Issue by yrashk** [npgall/cqengine#79]
Hi,

I am having an orchestration problem (OSGi components re-wiring) when an index is attempted to be added more than once, which causes and `IllegalStateException`. One workaround that works for me is to simply swallow this exception, but this is nowhere near a beautiful solution.

Is there any chance `removeIndex(index)` and/or `hasIndex(index)`  can be added to the `IndexedCollection` interface to solve this problem? I can also try keeping track of added indices on my end, but it seems like a duplication of what `CollectionQueryEngine` does.

**Comment by npgall** [comment]
There is already a getIndexes() method - would that help?

**Comment by yrashk** [comment]
Yep, `getIndexes()` did help. Thanks!
