### ISSUE TITLE
Extract *Attribute interfaces?

### ISSUE THREAD

**Issue by yrashk** [npgall/cqengine#80]
I have my own hierarchy for `SimpleAttribute` and `MultiValueAttribute` attributes and I am going to add `StandingQueryAttribute` to the mix as well. However, they all go through my own `AbstractAttribute` that takes care of a few aspects relevant to my framework:

https://github.com/eventsourcing/es4j/blob/master/eventsourcing-core/src/main/java/com/eventsourcing/index/SimpleAttribute.java
https://github.com/eventsourcing/es4j/blob/master/eventsourcing-core/src/main/java/com/eventsourcing/index/MultiValueAttribute.java
https://github.com/eventsourcing/es4j/blob/master/eventsourcing-core/src/main/java/com/eventsourcing/index/AbstractAttribute.java

While provisions for cqengine's own `SimpleAttribute` and `MultiValueAttribute` are *relatively* insignificant (simpler or more complex matching), I won't be able to take an advantage of `StandingQueryAttribute` unless I subclass from it (and I can't because of my own `AbstractAttribute` which I can't make an interface)

So I was thinking — may be we can extract `SimpleAttributeInterface`, `MultiValueAttributeInterface` and `StandingQueryInterface` (so that existing applications don't break) and make cqengine's engine do its type tests against these interfaces? This way an advantage of `StandingQueryAttribute` optimization can be taken.

What do you think?

**Comment by npgall** [comment]
Hi Yurii,

Yes we can probably do that. Can you submit a pull request for it?

**Comment by yrashk** [comment]
No longer relevant as #82 was closed.
