### ISSUE TITLE
[2 QUESTIONS and] Date comparisons on SQL Dialect queries.

### ISSUE THREAD

**Issue by jarey** [npgall/cqengine#88]
Hello,

I'll to be the quickest on my following two questions:

1. Are Date comparison supported on SQL Dialect queries under CQEngine.
The only way i can't get it working is treating the Dates as milliseconds and then registering a custom valueParser in order to convert those milliseconds specified in the query into Date type for the Date comparison against the attribute. Is there a better way? Any out-of-the-box support from CQEngine i'm not aware?

2. I've tested the comparisons relative to certain Date, using DateMathParser, with the expression like +0DAY etc supported by Solr and i think i just maybe fount a little issue.  I've tried the syntax as explained here: https://groups.google.com/d/msg/cqengine-discuss/Pvs0reAYC9U/G1u0Dm43BQAJ but the only way i got the parser working was if I specify the query the following way (i added the attribute date of type Date on the example Car class), please not the ' around the +0DAY:

`ResultSet<Car> results = parser.retrieve(cars, "SELECT * FROM orders WHERE (date< '+0DAY')");`

In other cases (if i write the query like  `(date< +0DAY)` ,or `(date< \"+0DAY\")` i got an exception on query parsing and the don't even reach the DateMathParser code.

Once entering the parsing specifying the date command between ' i needed to remove those characters in the DateMathParser code itself in order to get a working parsing of the command (if not removed exception inside the SolrParser raised).

Just wanted to ask you if something was wrong in my use of the mechanism or if it is a real issue around the use of that syntax.

Thank you very much in advance, any dateail you could need, please let me know..

PS: My changes in order to get that example working can be seen in order to compare between my changes and the code in your repository, here: 
- https://github.com/jarey/cqengine/blob/master/code/src/test/java/com/googlecode/cqengine/examples/parser/SQLQueryDemo.java#L50

- https://github.com/jarey/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/query/parser/cqn/support/DateMathParser.java#L81

**Comment by npgall** [comment]
Hi Jarey, you should ask questions in the discussion forum.

**Comment by jarey** [comment]
No problem, thanks for you time.

As i can tell, the same is happening for boolean comparisons, with the SQL expression; so with booleans, with the default boolean parser (com.googlecode.cqengine.query.parser.common.valuetypes.BooleanParser), the following happens:

- Queries like this will fail:
`ResultSet<Car> results = parser.retrieve(cars, "SELECT * FROM cars WHERE ('date' IS NULL AND 'hasGas' = true)");`
with the error: `"com.googlecode.cqengine.query.parser.common.InvalidQueryException: Failed to parse query at line 1:58: mismatched input 'true' expecting {NUMERIC_LITERAL, STRING_LITERAL}"`

- And queries like this will return uncorrect results, since the parser returns `Boolean.valueOF("'true'") `or `Boolean.valueOf("'false'")` wich in all cases is false for the comparison (note the single quotes again as part of the string value)..

Same happening as reported for the dates, just stripping the ' character from the strings solves the problem.

Obviosly there's nothing wrong with the engine itself, the only thing, in my opinion, is that the default parsers are not aligned with the SQLParser behaviour. 
I don't mind contributing rewriting all default parsers to work with SQLParser, but seems a pitty to not have support for all flavours of queries withing the same parsers bundled with the library for the basic types of objects. As it seems it could have an easy solution from someone who knows how the engine properly works (maybe my fix could seem an ugly patch from your perspective)

Any help you could need from me, just let me know (more case reproducing, testing, etc).

Thanks again.

**Comment by npgall** [comment]
Hi Jarey,

The issue with using boolean literals in the SQL dialect was a surprise, and it turned out to be a limitation of the Antlr grammar I was using for SQL. That grammar is based on SQL as understood by SQLite. As it turns out, SQLite does not support boolean literals, it uses only 0 or 1 :)

So I have added support for boolean literals in CQEngine's SQL dialect explicitly. This means that the shared BooleanParser will work correctly with both dialects. I also made it more robust against the issue you mentioned where values which surrounded by quotes can lead to incorrect parsing. Going forward, SQL boolean literals should not be surrounded by quotes at all, and it will throw and exception if they are.

I also added a variant of DateMathParser which can be used with the SQL dialect. It expects the date math expression to be enclosed in single quotes as is common in SQL.

Can you try that out?

**Comment by jarey** [comment]
Hi @npgall ,

Sure i will try it this afternoon and let you know. So far looking at the code changes all seems very good.
Thanks a lot for all the effort. Very appreciated.

As said i let you know if i find any problem with the changes in my tests, if all goes good i directly close the issue.

Thanks again.

**Comment by jarey** [comment]
Hello again @npgall,

As said i've tested the changes you made and all worked as expected.

So if someone come across this issue as a resume:

- Boolean comparison just work in SQL flavour by default, just like: `SELECT * FROM cars WHERE ('isElectric'  = true)` , with the boolean expected without single quotes.
- The `DataMathParser` in `com.googlecode.cqengine.query.parser.sql.support.DateMathParser` when registered in the parser, would parse the expressions in Solar expected syntax, for example: `SELECT * FROM cars WHERE ('buyDate' > '+2DAY')` with the date expression expected between single quotes.

Again thanks a lot for your effort on this.

Kind regards.

**Comment by npgall** [comment]
Thanks very much for your help too Jarey!
Best of luck!
