### ISSUE TITLE
Allow 1 subquery in OR

### ISSUE THREAD

**Issue by guai** [npgall/cqengine#95]
Or query does not allow fewer than 2 subqueries which causes IN query to fail on single-value lists either

**Comment by npgall** [comment]
Hi guai,

in() queries already do allow fewer than 2 subqueries. Which version of CQEngine are you referring to? Can you provide a test case which demonstrates the problem?

Thanks,
Niall

**Comment by guai** [comment]
I think I use the latest
```
    public Or(Collection<Query<O>> childQueries, boolean disjoint) {
        super(childQueries);
        if (this.size() < 2) {
            throw new IllegalStateException("An 'Or' query cannot have fewer than 2 child queries, " + childQueries.size() + " were supplied");
        }
        this.disjoint = disjoint;
        this.childQueries = childQueries;
    }
```
in `https://github.com/npgall/cqengine/blob/master/code/src/main/java/com/googlecode/cqengine/query/logical/Or.java`

As I can see in the code IN query converts into a bunch of ORs. And when I do not know the size of the collection  I want to use in IN query beforehand then it can or can not throw depending on its size. So its easy to miss it even on tests. And I do nat want po pollute my code with a lot of checks/wrappers etc. Even if its not that efficient.

**Comment by guai** [comment]
Sorry, I rechecked and that actually was not the latest version. Closing
