### ISSUE TITLE
OSGi overlapping package

### ISSUE THREAD

**Issue by npgall** [npgall/cqengine#96]
Details here:
https://github.com/npgall/cqengine-stream-support/issues/1

When that issue is fixed in the next release of cqengine-stream-support, CQEngine's dependency on that lib will need to be updated.

**Comment by npgall** [comment]
Done! This is fixed in CQEngine 2.9.0. It should sync to Maven central in a few hours.

**Comment by yrashk** [comment]
Thanks a lot!!! ❤️ 💜
