### ISSUE TITLE
No examples for more complex joins

### ISSUE THREAD

**Issue by ah-des** [npgall/cqengine#98]
Moved here: http://stackoverflow.com/questions/40358388/cqengine-join-more-than-two-collections

It might be worth keeping an eye on the cqengine page as well: http://stackoverflow.com/questions/tagged/cqengine

**Comment by npgall** [comment]
Done!
I've added an example to the end of the page [Joins.md](https://github.com/npgall/cqengine/blob/master/documentation/Joins.md).

I'll also post a Java 8 version of the solution to stackoverflow.
