### ISSUE TITLE
debugging IndexedCollection add method is too difficult

### ISSUE THREAD

**Issue by ghost** [npgall/cqengine#99]
See: http://stackoverflow.com/questions/40406059/cqengine-indexedcollection-add-causing-nullpointer

It would be much easier if the log output said something more like which field was null, why the nullpointer was caused (i.e. due to the index trying to get data from n field) and any other information that might help address the issue

It seems to stem from line 81 in AbstractMapBasedAttributeIndex.java

```
StoredResultSet<O> valueSet = indexMap.get(attributeValue);
```

The root cause is when an index returns a null

**Comment by npgall** [comment]
I think this is a documentation problem. It mentioned SimpleNullableAttribute and MultiValueNullableAttribute but didn't really explain when to use them.

The TL;DR is, if you get an NPE, it usually means you need to use a nullable attribute.

I've expanded the documentation on nullable attributes and on how null values are handled - there's now a section in the main Readme.md on "Null values". Hope that helps?!
